Repository mitodl/ol-infrastructure, pull requests merged in 2021-09, with the labels that each got.

#307 fix: move to old UA-style Google account
  src/bilder/images/edxapp/templates/common_values.yml
Labels: On Hold

#385 config: Add/Enable edx-username-changer plugin feature flag
  src/bilder/images/edxapp/templates/common_values.yml
Labels: DevOps, Needs Review

#386 fix: update Learning MFE BASE_URL to match PUBLIC_PATH
  pipelines/edx/mfe-frontend-app-learning-qa.yml
Labels: Needs Review

#387 Adding configuration to send edX logs and metrics to Grafana Cloud
  src/bilder/images/edxapp/deploy.py
  src/bilder/images/edxapp/files/nginx_status.conf
  src/bilder/images/edxapp/templates/vector/edxapp.yaml
  src/bilder/images/edxapp/templates/vector/metrics.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
  src/ol_infrastructure/applications/edxapp/__main__.py
Labels: MITx Online
