Repository mitodl/ol-infrastructure, pull requests merged in 2022-08, with the labels that each got.

#987 Setting up airbyte to use vault as its secret store.
  src/bilder/images/airbyte/files/docker-compose.yaml
  src/bilder/images/airbyte/templates/.env.tmpl
  src/bridge/lib/versions.py
  src/ol_infrastructure/applications/airbyte/__main__.py
  src/ol_infrastructure/applications/airbyte/airbyte_server_policy.hcl
Labels: Data, DevOps, Needs Review, Infrastructure

#996 SSO for Redash
  src/bilder/images/redash/deploy.py
  src/bilder/images/redash/files/.env.tmpl
  src/bilder/images/redash/files/attribute-map.xml
  src/bilder/images/redash/files/fastcgi.conf
  src/bilder/images/redash/files/fastcgi_params
  src/bilder/images/redash/files/mit-md-cert.pem
  src/bilder/images/redash/files/nginx.conf.tmpl
  src/bilder/images/redash/files/shib_clear_headers
  src/bilder/images/redash/files/shib_fastcgi_params
  src/bilder/images/redash/files/shibboleth2.xml.tmpl
  src/bilder/images/redash/templates/docker-compose.yaml.j2
  src/bridge/secrets/redash/redash.production.yaml
  src/bridge/secrets/redash/redash.qa.yaml
  src/ol_infrastructure/applications/redash/Pulumi.applications.redash.Production.yaml
  src/ol_infrastructure/applications/redash/Pulumi.applications.redash.QA.yaml
  src/ol_infrastructure/applications/redash/__main__.py
  src/ol_infrastructure/components/aws/auto_scale_group.py
Labels: enhancement, Data, DevOps, SaltStack Deprecation, Tech Debt

#1010 Created a migration runbook for upgrading redash
  src/ol_infrastructure/applications/redash/migration_runbook.md
Labels: documentation, Data, DevOps, InProgress

#1024 Remove disable_compat_19 from consul configs
  src/bilder/components/hashicorp/consul/models.py
Labels: bug, DevOps, Infrastructure

#1021 Adding a script and framework for backing up vault clusters to s3
  src/bilder/images/vault/deploy.py
  src/bilder/images/vault/files/raft_backup.sh
  src/bilder/images/vault/templates/vector/vault_logs.yaml
  src/bridge/secrets/pulumi/vault.operations.ci.yaml
  src/bridge/secrets/pulumi/vault.operations.production.yaml
  src/bridge/secrets/pulumi/vault.operations.qa.yaml
  src/ol_infrastructure/infrastructure/vault/Pulumi.infrastructure.vault.operations.CI.yaml
  src/ol_infrastructure/infrastructure/vault/Pulumi.infrastructure.vault.operations.Production.yaml
  src/ol_infrastructure/infrastructure/vault/Pulumi.infrastructure.vault.operations.QA.yaml
  src/ol_infrastructure/infrastructure/vault/__main__.py
  src/ol_infrastructure/lib/aws/ec2_helper.py
  src/ol_infrastructure/substructure/vault/auth/__main__.py
  src/ol_infrastructure/substructure/vault/auth/raft_backup_policy.hcl
  src/ol_infrastructure/substructure/vault/setup/Pulumi.substructure.vault.setup.operations.CI.yaml
  src/ol_infrastructure/substructure/vault/setup/Pulumi.substructure.vault.setup.operations.QA.yaml
Labels: enhancement, DevOps, Infrastructure, Monitoring and Alerting, InProgress

#1008 Tm/airbyte fixup
  src/bilder/images/airbyte/airbyte.pkr.hcl
  src/bilder/images/airbyte/deploy.py
  src/ol_infrastructure/applications/airbyte/Pulumi.applications.airbyte.Production.yaml
  src/ol_infrastructure/applications/airbyte/Pulumi.applications.airbyte.QA.yaml
  src/ol_infrastructure/applications/airbyte/__main__.py
  src/ol_infrastructure/applications/dagster/__main__.py
Labels: Data

#1039 Adding a PATH env var to the cron job executing raft_backup.sh
  src/ol_infrastructure/infrastructure/vault/__main__.py
Labels: bug, DevOps
