Repository mitodl/ol-infrastructure, pull requests merged in 2022-11, with the labels that each got.

#1164 Created a basic framework for attaching slack notifications to any concourse job.
  src/concourse/lib/notifications.md
  src/concourse/lib/notifications.py
  src/concourse/lib/resource_types.py
  src/concourse/lib/resources.py
  src/concourse/pipelines/infrastructure/grafana_cloud/pipeline.py
Labels: DevOps, Needs Review

#1189 vault 1.12.0 hotfix
  src/bilder/images/vault/files/vault_env_script.sh
Labels: bug, DevOps

#1190 Workaround for current bad release of vector
  src/bilder/components/vector/steps.py
Labels: bug, DevOps

#1188 refactor: Use version info module for edX in MFE pipeline
  src/bilder/images/edxapp/deploy.py
  src/bilder/images/edxapp/prebuild.py
  src/bridge/settings/openedx/accessors.py
  src/bridge/settings/openedx/types.py
  src/bridge/settings/openedx/version_matrix.py
  src/concourse/lib/models/fragment.py
  src/concourse/pipelines/open_edx/edx_platform/meta.py
  src/concourse/pipelines/open_edx/edx_platform/packer_pulumi_pipeline.py
  src/concourse/pipelines/open_edx/mfe/meta.py
  src/concourse/pipelines/open_edx/mfe/pipeline.py
  src/concourse/pipelines/open_edx/mfe/values.py
Labels: Open edX

#1192 Enable feature flag for zero grades
  src/bilder/images/edxapp/templates/edxapp/mitx-staging/common_values.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitx/common_values.yml.tmpl
Labels: Needs Review

#1193 Online-1170 Add Settings for max file upload size for discussions
  src/bilder/images/edxapp/templates/edxapp/mitxonline/lms_only.yml.tmpl
Labels: Needs Review

#1171 feat: Add config for deploying course authoring MFE
  src/bilder/images/edxapp/templates/edxapp/mitx-staging/studio_only.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitx/studio_only.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitxonline/studio_only.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/xpro/studio_only.yml.tmpl
  src/bridge/settings/openedx/version_matrix.py
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.CI.yaml
Labels: MITx Online, Open edX

#1196 config: Use Fastly for edX studio to support MFEs
  src/bilder/images/edxapp/templates/edxapp/mitx-staging/studio_only.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitx/studio_only.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitxonline/studio_only.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/xpro/studio_only.yml.tmpl
  src/ol_infrastructure/applications/edxapp/__main__.py
Labels: MITx Online, Open edX, xPRO

#1197 config: Enable course search for xPro and residential
  src/bilder/images/edxapp/templates/edxapp/mitx-staging/common_values.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitx/common_values.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/xpro/common_values.yml.tmpl
Labels: Open edX, xPRO

#1203 Online-1182 Add marketing configs and URLs
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#1202 config: Enable library authoring MFE and Blockstore for Olive
  src/bilder/images/edxapp/templates/edxapp/mitx-staging/common_values.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitx-staging/studio_only.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitx/common_values.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitx/studio_only.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitxonline/studio_only.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/xpro/common_values.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/xpro/studio_only.yml.tmpl
Labels: Open edX, xPRO

#1204 Added configs for dynaconf
  src/bilder/images/dagster/files/.env.tmpl
Labels: Data

#1214 Expire Vault backups out of S3 after 1 year
  src/bridge/settings/openedx/types.py
  src/ol_infrastructure/infrastructure/vault/__main__.py
Labels: enhancement, DevOps, Infrastructure, Tech Debt, InProgress

#1135 Md/ovs migration2 - Checkpoint
  .pre-commit-config.yaml
  src/bilder/images/odl_video_service/BUILD
  src/bilder/images/odl_video_service/__init__.py
  src/bilder/images/odl_video_service/deploy.py
  src/bilder/images/odl_video_service/files/.env.tmpl
  src/bilder/images/odl_video_service/files/attribute-map.xml
  src/bilder/images/odl_video_service/files/docker-compose.yaml.tmpl
  src/bilder/images/odl_video_service/files/fastcgi_params
  src/bilder/images/odl_video_service/files/logging.conf
  src/bilder/images/odl_video_service/files/nginx_with_shib.conf.tmpl
  src/bilder/images/odl_video_service/files/nginx_wo_shib.conf.tmpl
  src/bilder/images/odl_video_service/files/shib_clear_headers
  src/bilder/images/odl_video_service/files/shib_fastcgi_params
  src/bilder/images/odl_video_service/files/shib_params
  src/bilder/images/odl_video_service/files/shibboleth2.xml.tmpl
  src/bilder/images/odl_video_service/files/uwsgi_params
  src/bilder/images/odl_video_service/odl_video_service.pkr.hcl
  src/bilder/lib/template_helpers.py
  src/bridge/lib/versions.py
  src/bridge/secrets/odl_video_service/data.ci.yaml
  src/bridge/secrets/odl_video_service/data.qa.yaml
  src/concourse/lib/resources.py
  src/concourse/pipelines/infrastructure/ovs/docker_pipeline.py
  src/ol_infrastructure/applications/odl_video_service/Pulumi.applications.odl_video_service.CI.yaml
  src/ol_infrastructure/applications/odl_video_service/Pulumi.applications.odl_video_service.Production.yaml
  src/ol_infrastructure/applications/odl_video_service/Pulumi.applications.odl_video_service.QA.yaml
  src/ol_infrastructure/applications/odl_video_service/Pulumi.yaml
  src/ol_infrastructure/applications/odl_video_service/__init__.py
  src/ol_infrastructure/applications/odl_video_service/__main__.py
  src/ol_infrastructure/applications/odl_video_service/odl_video_service_server_policy.hcl
Labels: enhancement, DevOps, Infrastructure, SaltStack Deprecation

#1220 Revert Vector version pinning
  src/bilder/components/vector/steps.py
Labels: bug, DevOps, Monitoring and Alerting
