Repository mitodl/ol-infrastructure, pull requests merged in 2022-03, with the labels that each got.

#619 Bundle concourse resource_types
  pipelines/resources/README.md
  pipelines/resources/build-concourse-resources.yaml
  pipelines/resources/rclone.yaml
  pipelines/resources/s3-sync.yaml
  pipelines/resources/vars_rclone.yaml
  pipelines/resources/vars_s3-sync.yaml
  src/bilder/components/concourse/models.py
  src/bilder/components/concourse/steps.py
  src/bilder/images/concourse/deploy.py
Labels: enhancement, DevOps, Infrastructure, OCW

#641 asadiqbal08/Config "SHOW_FULLNAME" for learning MFE Header
  pipelines/edx/mfe-frontend-app-learning-xpro-ci.yaml
  pipelines/edx/mfe-frontend-app-learning-xpro-production.yaml
  pipelines/edx/mfe-frontend-app-learning-xpro-qa.yaml
Labels: Needs Review

#647 Initial commit of opensearch enhancmenets
  src/ol_infrastructure/applications/mit_open/__main__.py
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.apps.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.apps.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.apps.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/__main__.py
  src/ol_infrastructure/infrastructure/consul/Pulumi.infrastructure.consul.apps.CI.yaml
Labels: enhancement, DevOps, Infrastructure

#650 Enable disk metric collection with vector
  src/bilder/components/vector/templates/host_metrics.yaml
Labels: enhancement, DevOps, Infrastructure

#663 Created the OCW CI environment buckets.
  src/ol_infrastructure/applications/ocw_site/Pulumi.applications.ocw_site.CI.yaml
Labels: DevOps, OCW

#680 Vector Proxy
  pipelines/infrastructure/vector_proxy_ami_new_release.yaml
  src/bilder/components/vector/models.py
  src/bilder/components/vector/steps.py
  src/bilder/images/variables.pkr.hcl
  src/bilder/images/vector_log_proxy/BUILD
  src/bilder/images/vector_log_proxy/__init__.py
  src/bilder/images/vector_log_proxy/deploy.py
  src/bilder/images/vector_log_proxy/templates/vector/vector-log-proxy.yaml.j2
  src/bridge/secrets/vector/heroku_proxy.ci.yaml
  src/bridge/secrets/vector/heroku_proxy.production.yaml
  src/bridge/secrets/vector/heroku_proxy.qa.yaml
  src/ol_infrastructure/infrastructure/vector_log_proxy/Pulumi.infrastructure.vector_log_proxy.operations.CI.yaml
  src/ol_infrastructure/infrastructure/vector_log_proxy/Pulumi.infrastructure.vector_log_proxy.operations.Production.yaml
  src/ol_infrastructure/infrastructure/vector_log_proxy/Pulumi.infrastructure.vector_log_proxy.operations.QA.yaml
  src/ol_infrastructure/infrastructure/vector_log_proxy/Pulumi.yaml
  src/ol_infrastructure/infrastructure/vector_log_proxy/README.md
  src/ol_infrastructure/infrastructure/vector_log_proxy/__init__.py
  src/ol_infrastructure/infrastructure/vector_log_proxy/__main__.py
  src/ol_infrastructure/infrastructure/vector_log_proxy/vector_log_proxy_policy.hcl
Labels: DevOps, Maintenance

#696 Make the concourse AMI builds run in parallel
  pipelines/infrastructure/concourse_ami_new_release.yaml
Labels: DevOps

#699 ocw-content backup adjustments
  pipelines/ocw/backup-ocw-content/backup-ocw-content.yaml
  src/ol_infrastructure/applications/ocw_site/__main__.py
Labels: DevOps, Needs Review, OCW

#714 Adding handling of OCW site domains to Pulumi
  .pre-commit-config.yaml
  src/ol_infrastructure/applications/ocw_site/Pulumi.applications.ocw_site.Production.yaml
  src/ol_infrastructure/applications/ocw_site/Pulumi.applications.ocw_site.QA.yaml
  src/ol_infrastructure/applications/ocw_site/__main__.py
  src/ol_infrastructure/lib/aws/iam_helper.py
Labels: OCW

#725 Small to cloud custodian pipelines
  cloud_custodian/tag_ebs_resources_for_cleanup.yaml
  pipelines/infrastructure/cloud_custodian.yaml
Labels: bug, DevOps
