Repository mitodl/ol-infrastructure, pull requests merged in 2022-04, with the labels that each got.

#726 Revert "Merge pull request #717 from mitodl/renovate/node-17.x"
  dockerfiles/ocw/node-hugo/Dockerfile
Labels: Needs Review

#740 Public Opensearch clusters -> Finegrained access control
  .pre-commit-config.yaml
  src/bridge/secrets/opensearch/opensearch.apps.ci.yaml
  src/bridge/secrets/opensearch/opensearch.apps.production.yaml
  src/bridge/secrets/opensearch/opensearch.apps.qa.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/README.md
  src/ol_infrastructure/infrastructure/aws/opensearch/__main__.py
  src/ol_infrastructure/infrastructure/aws/opensearch/bootstrap_security_config.py
Labels: DevOps, Infrastructure

#736 Create CI pipelines for edxapp AMI builds
  pipelines/infrastructure/edxapp/edx_base_ami.yaml
  pipelines/infrastructure/edxapp/edx_base_ami_vars/maple.yaml
  pipelines/infrastructure/edxapp/edx_base_ami_vars/master.yaml
  pipelines/infrastructure/edxapp/edx_custom_ami.yaml
  pipelines/infrastructure/edxapp/edx_custom_ami_vars/mitx-staging.yaml
  pipelines/infrastructure/edxapp/edx_custom_ami_vars/mitx.yaml
  pipelines/infrastructure/edxapp/edx_custom_ami_vars/mitxonline.yaml
  pipelines/infrastructure/edxapp/edx_custom_ami_vars/xpro.yaml
  src/bilder/images/edxapp/packer_vars/maple.pkrvars.hcl
  src/bilder/images/edxapp/packer_vars/master.pkrvars.hcl
Labels: enhancement

#737 Issue 707 grizzly pipeline
  pipelines/infrastructure/grizzly/README.md
  pipelines/infrastructure/grizzly/grizzly.yaml
  pipelines/infrastructure/grizzly/managed_vars.yaml
  src/bilder/images/concourse/deploy.py
Labels: DevOps

#751 Support removal of edX Python packages
  src/bilder/images/edxapp/deploy.py
  src/bilder/images/edxapp/group_data/all.py
Labels: Needs Review, MITx Online

#764 Upgrade the PyInfra dependency to the v2 major release
  poetry.lock
  pyproject.toml
  src/bilder/components/baseline/steps.py
  src/bilder/components/caddy/sample_deploy.py
  src/bilder/components/caddy/steps.py
  src/bilder/components/concourse/sample_deploy.py
  src/bilder/components/concourse/steps.py
  src/bilder/components/hashicorp/consul/steps.py
  src/bilder/components/hashicorp/consul_template/steps.py
  src/bilder/components/hashicorp/steps.py
  src/bilder/components/hashicorp/vault/steps.py
  src/bilder/components/vector/sample_deploy.py
  src/bilder/components/vector/steps.py
  src/bilder/images/concourse/deploy.py
  src/bilder/images/consul/deploy.py
  src/bilder/images/edxapp/deploy.py
  src/bilder/images/edxapp/plugins/git_export_import.py
  src/bilder/images/vault/deploy.py
  src/bilder/images/vector_log_proxy/deploy.py
Labels: Needs Review

#767 Setting an explicit worker disk size for edxapp mitx production.
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.Production.yaml
Labels: DevOps, MITx Online, Maintenance, Infrastructure

#783 monitoring documentation
  docs/monitoring/inventory.md
  docs/monitoring/overview.md
Labels: documentation, DevOps, Needs Review, Infrastructure
