Repository mitodl/ol-infrastructure, pull requests merged in 2022-10, with the labels that each got.

#1111 Scale up MIT Open Opensearch
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open.Production.yaml
Labels: DevOps, Infrastructure

#1124 PyInfra component definition for Traefik proxy server
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  src/bilder/components/traefik/BUILD
  src/bilder/components/traefik/README.md
  src/bilder/components/traefik/models/component.py
  src/bilder/components/traefik/models/traefik_file_provider.py
  src/bilder/components/traefik/models/traefik_static.py
  src/bilder/components/traefik/packer.pkr.hcl
  src/bilder/components/traefik/sample_deploy.py
  src/bilder/components/traefik/steps.py
  src/bilder/components/traefik/templates/traefik.service.j2
Labels: Infrastructure

#1125 refactor: Use Traefik for proxying Vault web traffic instead of Caddy
  src/bilder/components/traefik/templates/traefik.service.j2
  src/bilder/images/vault/deploy.py
  src/bilder/images/vault/files/traefik/dynamic_config.yaml
  src/bilder/images/vault/files/traefik/static_config.yaml
  src/bilder/images/vault/templates/caddyfile.j2
  src/bridge/lib/versions.py
  src/ol_infrastructure/infrastructure/vault/__main__.py
Labels: bug, DevOps, Infrastructure

#1120 Related to ol-data PR#356
  src/bilder/images/dagster/files/.env.tmpl
  src/bilder/images/dagster/templates/docker-compose.yaml.j2
  src/ol_infrastructure/applications/dagster/__main__.py
Labels: Data

#1133 upgrade hugo version in ocw-course-publisher
  dockerfiles/ocw/node-hugo/Dockerfile
  dockerfiles/ocw/node-hugo/tag
  src/concourse/pipelines/container_images/openedx_tubular.py
  src/concourse/pipelines/infrastructure/airbyte/packer_pulumi_pipeline.py
  src/concourse/pipelines/infrastructure/aws/pulumi_pipeline.py
  src/concourse/pipelines/infrastructure/cloud_custodian/pipeline.py
  src/concourse/pipelines/infrastructure/concourse/packer_pulumi_pipeline.py
  src/concourse/pipelines/infrastructure/consul/packer_pulumi_pipeline.py
  src/concourse/pipelines/infrastructure/dagster/packer_pulumi_pipeline.py
  src/concourse/pipelines/infrastructure/docker_baseline/packer_pipeline.py
  src/concourse/pipelines/infrastructure/grafana_cloud/pipeline.py
  src/concourse/pipelines/infrastructure/ocw_site/pipeline.py
  src/concourse/pipelines/infrastructure/ovs/docker_pipeline.py
  src/concourse/pipelines/infrastructure/redash/packer_pulumi_pipeline.py
  src/concourse/pipelines/infrastructure/tika/packer_pulumi_pipeline.py
  src/concourse/pipelines/infrastructure/vault/packer_pulumi_pipeline.py
  src/concourse/pipelines/infrastructure/vector_log_proxy/packer_pulumi_pipeline.py
  src/concourse/pipelines/open_edx/mfe/meta.py
  src/concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Needs Review

#1136 concourse pipeline breakdown documentation
  src/concourse/docs/concourse_wrapper_breakdown.pdf
Labels: documentation, DevOps

#1148 Concourse pipeline and meta pipeline for deploying edxapp releases
  pipelines/infrastructure/ami_builds/edxapp/edx_base_ami.yaml
  pipelines/infrastructure/ami_builds/edxapp/edx_base_ami_vars/maple.yaml
  pipelines/infrastructure/ami_builds/edxapp/edx_base_ami_vars/master.yaml
  pipelines/infrastructure/ami_builds/edxapp/edx_base_ami_vars/nutmeg.yaml
  pipelines/infrastructure/ami_builds/edxapp/edx_custom_ami.yaml
  pipelines/infrastructure/ami_builds/edxapp/edx_custom_ami_vars/mitx-staging.yaml
  pipelines/infrastructure/ami_builds/edxapp/edx_custom_ami_vars/mitx.yaml
  pipelines/infrastructure/ami_builds/edxapp/edx_custom_ami_vars/mitxonline.yaml
  pipelines/infrastructure/ami_builds/edxapp/edx_custom_ami_vars/xpro.yaml
  src/bilder/images/edxapp/packer_vars/olive.pkrvars.hcl
  src/concourse/lib/jobs/infrastructure.py
  src/concourse/pipelines/open_edx/edx_platform/meta.py
  src/concourse/pipelines/open_edx/edx_platform/packer_pulumi_pipeline.py
  src/concourse/pipelines/open_edx/edx_platform/pipeline_vars.py
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.CI.yaml
Labels: Open edX

#1153 config: Update balancing algorithm for lms
  src/ol_infrastructure/applications/edxapp/__main__.py
Labels: Open edX

#1158 Vector log rotation patch
  src/bilder/images/edxapp/templates/vector/edxapp_logs.yaml.j2
Labels: bug, DevOps, Monitoring and Alerting

#1159 Adding redirects for two Gil Strang YouTube playlists
  src/ol_infrastructure/applications/ocw_site/redirect_dict
Labels: Waiting on Author

#1161 Adding redirect for 24.908
  src/ol_infrastructure/applications/ocw_site/redirect_dict
Labels: Waiting on Author

#1160 Fix Trino to Redash permissions
  src/ol_infrastructure/infrastructure/aws/data_warehouse/__main__.py
Labels: bug

#1023 Added redirect link for CMS-W courses
  src/ol_infrastructure/applications/ocw_site/redirect_dict
Labels: Waiting on Author

#1174 Create a single source of truth for deployment, version, and application details for Open edX
  src/bilder/images/edxapp/deploy.py
  src/bilder/images/edxapp/lib.py
  src/bilder/images/edxapp/prebuild.py
  src/bridge/settings/openedx/version_matrix.py
  src/concourse/pipelines/open_edx/edx_platform/packer_pulumi_pipeline.py
  src/concourse/pipelines/open_edx/edx_platform/pipeline_vars.py
Labels: Open edX

#1173 Added course scholar redirects
  src/ol_infrastructure/applications/ocw_site/redirect_dict
Labels: Needs Review
