Repository mitodl/ol-infrastructure, pull requests merged in 2022-01, with the labels that each got.

#530 restrict only third party auth for access
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml
Labels: Needs Review

#536 Updating discovery of edxapp DB from DNS to template
  src/bilder/images/edxapp/templates/edxapp/mitx-staging/common_values.yml
  src/bilder/images/edxapp/templates/edxapp/mitx/common_values.yml
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml
  src/bilder/images/edxapp/templates/edxapp/xpro/common_values.yml
  src/ol_infrastructure/applications/edxapp/__main__.py
Labels: MITx Online

#543 Adding central location to track installed service versions
  src/bilder/images/concourse/deploy.py
  src/bilder/images/consul/__init__.py
  src/bilder/images/consul/deploy.py
  src/bilder/images/edxapp/deploy.py
  src/bilder/images/vault/__init__.py
  src/bilder/images/vault/deploy.py
  src/bridge/lib/versions.py
Labels: Maintenance

#548 Revert "restrict only third party auth for access"
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml
Labels: Needs Review
