Repository mitodl/ol-infrastructure, pull requests merged in 2023-09, with the labels that each got.

#1746 Resize redis mitxonline production nodes
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.Production.yaml
Labels: DevOps

#1747 Fixing units on RDS latency monitors to enable data collection.
  src/ol_infrastructure/components/aws/cloudwatch.py
  src/ol_infrastructure/components/aws/database.py
Labels: bug, Needs Review, Monitoring and Alerting

#1742 Setting up vault global secrets
  src/bridge/secrets/vault/secrets.production.yaml
  src/bridge/secrets/vault/secrets.qa.yaml
  src/ol_infrastructure/substructure/vault/secrets/Pulumi.substructure.vault.secrets.Production.yaml
  src/ol_infrastructure/substructure/vault/secrets/Pulumi.substructure.vault.secrets.QA.yaml
  src/ol_infrastructure/substructure/vault/secrets/Pulumi.yaml
  src/ol_infrastructure/substructure/vault/secrets/__init__.py
  src/ol_infrastructure/substructure/vault/secrets/__main__.py
Labels: DevOps

#1754 feat: enable mktg site
  src/bilder/images/edxapp/templates/edxapp/xpro/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/common_values.yml.tmpl
Labels: Needs Review

#1759 Switch mitx-staging production over to the docker framework.
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.Production.yaml
Labels: DevOps, Open edX, product:residential

#1761 Disable RDS monitoring for dagster database
  src/ol_infrastructure/applications/dagster/__main__.py
Labels: Data, Monitoring and Alerting, product:data-platform

#1722 vault backup guide
  docs/how_to/faking_it_with_consul_and_vault.md
  docs/how_to/restore_vault_backups.md
Labels: documentation

#1756 Initial commit of the semantic-poc ami and associated infrastructure.
  src/bilder/images/semantic/__init__.py
  src/bilder/images/semantic/deploy.py
  src/bilder/images/semantic/files/docker-compose.yaml
  src/bilder/images/semantic/files/nginx.conf
  src/bilder/images/semantic/semantic.pkr.hcl
  src/ol_infrastructure/applications/semantic/Pulumi.applications.semantic.Production.yaml
  src/ol_infrastructure/applications/semantic/Pulumi.yaml
  src/ol_infrastructure/applications/semantic/__init__.py
  src/ol_infrastructure/applications/semantic/__main__.py
  src/ol_infrastructure/applications/semantic/semantic_server_policy.hcl
Labels: DevOps, Needs Review, Infrastructure, POC

#1762 Add BULK_EMAIL_RETRY_DELAY_BETWEEN_SENDS
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/lms_only.yml.tmpl
Labels: DevOps

#1758 feat: set COURSES_INVITE_ONLY to true
  src/bilder/images/edxapp/templates/edxapp/xpro/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/common_values.yml.tmpl
Labels: Needs Review

#1766 Moves proctortrack consul configs to edxapp
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
  src/ol_infrastructure/applications/edxapp/__main__.py
  src/ol_infrastructure/applications/mitxonline/Pulumi.applications.mitxonline.Production.yaml
  src/ol_infrastructure/applications/mitxonline/Pulumi.applications.mitxonline.QA.yaml
  src/ol_infrastructure/applications/mitxonline/__main__.py
Labels: DevOps, Needs Review, product:mitx-online

#1780 residential to docker framework
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.Production.yaml
Labels: DevOps, Needs Review, Open edX, product:residential

#1783 Enable keycloak metrics
  src/bilder/images/keycloak/files/.env.tmpl
  src/bridge/secrets/keycloak/data.ci.yaml
  src/bridge/secrets/keycloak/data.production.yaml
  src/bridge/secrets/keycloak/data.qa.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#1785 Fix Moira cert for OVS
  docs/how_to/moira_certificates.md
  src/bridge/secrets/odl_video_service/data.production.yaml
  src/bridge/secrets/odl_video_service/data.qa.yaml
Labels: documentation, DevOps, Needs Review, product:ovs

#1787 Add vector config for keycloak logging and metrics
  src/bilder/images/keycloak/deploy.py
  src/bilder/images/keycloak/files/.env.tmpl
  src/bilder/images/keycloak/templates/vector/keycloak_logs_metrics.yaml
  src/bridge/lib/magic_numbers.py
  src/bridge/secrets/keycloak/data.ci.yaml
  src/bridge/secrets/keycloak/data.production.yaml
  src/bridge/secrets/keycloak/data.qa.yaml
Labels: DevOps
