Repository mitodl/ol-infrastructure, pull requests merged in 2023-01, with the labels that each got.

#1292 POC: Instance Refresh jobs in concourse --
  src/concourse/lib/tasks.py
  src/concourse/pipelines/infrastructure/concourse/instance_refresh.py
  src/ol_infrastructure/applications/concourse/Pulumi.applications.concourse.CI.yaml
  src/ol_infrastructure/applications/concourse/__main__.py
  src/ol_infrastructure/applications/concourse/iam_policies/cloud_custodian.py
  src/ol_infrastructure/applications/concourse/iam_policies/infra.py
Labels: enhancement, DevOps, Needs Review, Infrastructure

#1293 Docker logging enhancements pt 3
  src/bilder/images/docker_baseline_ami/templates/vector/docker_logs.yaml.j2
Labels: enhancement, DevOps, Monitoring and Alerting

#1295 AMI and snapshot cleanup policies for cloud custodian
  cloud_custodian/cleanup_ebs_resources.yaml
  cloud_custodian/tag_ebs_resources_for_cleanup.yaml
Labels: DevOps, Needs Review, Infrastructure

#1308 Md/issue 1249 - OVS Pipeline
  setup.cfg
  src/bilder/images/odl_video_service/deploy.py
  src/bilder/images/odl_video_service/files/docker-compose.yaml.tmpl
  src/concourse/lib/jobs/infrastructure.py
  src/concourse/pipelines/infrastructure/ovs/docker_packer_pulumi_pipeline.py
  src/concourse/pipelines/infrastructure/ovs/docker_pipeline.py
  src/ol_infrastructure/applications/edxapp/__main__.py
  src/ol_infrastructure/infrastructure/mongodb_atlas/__main__.py
Labels: enhancement, DevOps, Needs Review, Tech Debt

#1315 S3 bucket to use for edxorg course tarballs
  src/ol_infrastructure/applications/dagster/Pulumi.applications.dagster.Production.yaml
  src/ol_infrastructure/applications/dagster/Pulumi.applications.dagster.QA.yaml
  src/ol_infrastructure/applications/dagster/__main__.py
Labels: DevOps

#1316 Read permission to course tarballs for open app
  src/ol_infrastructure/applications/mit_open/__main__.py
Labels: DevOps

#1317 Task to block a job for an aws instance refresh
  src/concourse/lib/tasks.py
  src/concourse/pipelines/infrastructure/concourse/instance_refresh.py
Labels: enhancement, DevOps, Needs Review

#1314 automated datasouce management for redash
  src/bilder/images/redash/deploy.py
  src/bilder/images/redash/files/datasources.yaml.tmpl
  src/bilder/images/redash/files/update_datasources.py
  src/bridge/secrets/redash/redash.production.yaml
  src/bridge/secrets/redash/redash.qa.yaml
  src/ol_infrastructure/applications/redash/DATASOURCE_MANAGEMENT.md
  src/ol_infrastructure/applications/redash/Pulumi.applications.redash.Production.yaml
  src/ol_infrastructure/applications/redash/Pulumi.applications.redash.QA.yaml
  src/ol_infrastructure/applications/redash/__main__.py
  src/ol_infrastructure/applications/redash/redash_server_policy.hcl
Labels: documentation, enhancement, DevOps, Needs Review, Infrastructure, SaltStack Deprecation, Tech Debt

#1318 aws.GetAmi -> aws.ec2.GetAmi
  src/ol_infrastructure/applications/odl_video_service/__main__.py
  src/ol_infrastructure/applications/redash/__main__.py
Labels: DevOps, Tech Debt

#1322 edxapp elasticache instance enhancements
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.Production.yaml
  src/ol_infrastructure/applications/edxapp/__main__.py
  src/ol_infrastructure/lib/aws/cache_helper.py
  src/ol_infrastructure/lib/stack_defaults.py
Labels: enhancement, DevOps, Needs Review, Infrastructure

#1325 config: update support/help link for MITxOnline
  src/concourse/pipelines/open_edx/mfe/values.py
Labels: Needs Review

#1324 Updating forum instance sizing to default to t3a.micro which it fits …
  src/ol_infrastructure/applications/forum/Pulumi.applications.forum.mitxonline.Production.yaml
  src/ol_infrastructure/applications/forum/Pulumi.applications.forum.xpro.Production.yaml
  src/ol_infrastructure/applications/forum/__main__.py
Labels: DevOps, Needs Review, Infrastructure

#1326 Rightsizing xqueue instances to t3a.micro in all environments.
  src/ol_infrastructure/applications/xqueue/__main__.py
Labels: DevOps, Needs Review, Infrastructure

#1327 Rightsizing codejail environments to t3a.micro
  src/ol_infrastructure/applications/codejail/Pulumi.applications.codejail.mitx-staging.CI.yaml
  src/ol_infrastructure/applications/codejail/Pulumi.applications.codejail.mitx-staging.Production.yaml
  src/ol_infrastructure/applications/codejail/Pulumi.applications.codejail.mitx-staging.QA.yaml
  src/ol_infrastructure/applications/codejail/Pulumi.applications.codejail.mitx.CI.yaml
  src/ol_infrastructure/applications/codejail/Pulumi.applications.codejail.mitx.Production.yaml
  src/ol_infrastructure/applications/codejail/Pulumi.applications.codejail.mitx.QA.yaml
  src/ol_infrastructure/applications/codejail/Pulumi.applications.codejail.mitxonline.Production.yaml
  src/ol_infrastructure/applications/codejail/Pulumi.applications.codejail.xpro.Production.yaml
  src/ol_infrastructure/applications/codejail/__main__.py
Labels: DevOps, Needs Review, Infrastructure

#1339 Setting MONGOID_MAX_RETRIES and MONGOID_TIMEOUT for forum.
  src/bilder/images/forum/files/forum.env.j2
Labels: DevOps, Infrastructure
