Repository mitodl/ol-infrastructure, pull requests merged in 2023-05, with the labels that each got.

#1495 keycloak and pki fixups
  src/concourse/pipelines/infrastructure/keycloak/docker_packer_pulumi_pipeline.py
  src/ol_infrastructure/applications/keycloak/__main__.py
  src/ol_infrastructure/components/services/vault.py
  src/ol_infrastructure/substructure/vault/pki/__main__.py
Labels: enhancement, DevOps, Infrastructure

#1499 PKI Relationship fixes
  src/ol_infrastructure/substructure/vault/pki/__main__.py
Labels: bug, DevOps

#1302 Update user retirement states
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: do not merge

#1501 turn off annotations in OVS RC
  src/ol_infrastructure/applications/odl_video_service/Pulumi.applications.odl_video_service.QA.yaml
Labels: DevOps

#1512 Concourse infrastructure worker scale up
  src/ol_infrastructure/applications/concourse/Pulumi.applications.concourse.Production.yaml
Labels: enhancement, DevOps, Infrastructure

#1511 add ENABLE_NEW_BULK_EMAIL_EXPERIENCE ...
  src/bilder/images/edxapp/templates/edxapp/mitx-staging/common_values.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitx/common_values.yml.tmpl
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#1532 Upgrade ocw go to 1.20.4 and hugo to 0.112.0
  dockerfiles/ocw/node-hugo/Dockerfile
  dockerfiles/ocw/node-hugo/tag
  src/concourse/pipelines/examples/hello.py
Labels: Needs Review

#1503 Upgrading MIT Open elasticsearch clusters to 7.10
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open.QA.yaml
Labels: DevOps, Maintenance, Infrastructure

#1537 Add framework tagging to edxapp AMI builds and deploys
  src/bilder/images/edxapp/custom_install.pkr.hcl
  src/bilder/images/edxapp/edxapp_base.pkr.hcl
  src/ol_infrastructure/applications/edxapp/__main__.py
Labels: DevOps, Needs Review, Open edX

#1542 config,fix: Enable segmented caching for large files in OCW Fastly
  src/ol_infrastructure/applications/ocw_site/__main__.py
  src/ol_infrastructure/applications/ocw_site/snippets/large_object_segmented_caching.vcl
Labels: product:ocw

#1460 Keycloak realm config
  poetry.lock
  pyproject.toml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.yaml
  src/ol_infrastructure/substructure/keycloak/__init__.py
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps
