Repository mitodl/ol-infrastructure, pull requests merged in 2023-10, with the labels that each got.

#1793 Create AWS PrivateLinks between Mongo and DataVPC
  src/ol_concourse/pipelines/infrastructure/mongodb_atlas/__init__.py
  src/ol_concourse/pipelines/infrastructure/mongodb_atlas/pulumi_pipeline.py
  src/ol_infrastructure/infrastructure/mongodb_atlas/Pulumi.infrastructure.mongodb_atlas.mitx.Production.yaml
  src/ol_infrastructure/infrastructure/mongodb_atlas/Pulumi.infrastructure.mongodb_atlas.mitx.QA.yaml
  src/ol_infrastructure/infrastructure/mongodb_atlas/Pulumi.infrastructure.mongodb_atlas.mitxonline.Production.yaml
  src/ol_infrastructure/infrastructure/mongodb_atlas/Pulumi.infrastructure.mongodb_atlas.mitxonline.QA.yaml
  src/ol_infrastructure/infrastructure/mongodb_atlas/Pulumi.infrastructure.mongodb_atlas.xpro.Production.yaml
  src/ol_infrastructure/infrastructure/mongodb_atlas/Pulumi.infrastructure.mongodb_atlas.xpro.QA.yaml
  src/ol_infrastructure/infrastructure/mongodb_atlas/__main__.py
Labels: enhancement, Data, DevOps, Needs Review, product:data-platform

#1808 Created a substructure stack for consul-data-ci
  src/ol_infrastructure/substructure/consul/Pulumi.substructure.consul.data.CI.yaml
Labels: DevOps, Infrastructure

#1813 Giving dagster production 1TB.
  src/ol_infrastructure/applications/dagster/Pulumi.applications.dagster.Production.yaml
Labels: bug, Data, product:data-platform

#1814 Issue 1410 - Fastly log data enhancements
  src/ol_infrastructure/lib/fastly.py
Labels: Data, DevOps, Needs Review, Monitoring and Alerting, product:data-platform

#1826 Airbyte -> fastly s3 bucket
  src/ol_infrastructure/applications/airbyte/__main__.py
Labels: Data, DevOps, product:data-platform

#1840 fix: fix default xmodule class name
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#1842 Issue 1629 - Log shipping for edxapp fastly distributions
  src/ol_infrastructure/applications/edxapp/__main__.py
  src/ol_infrastructure/applications/ocw_site/__main__.py
  src/ol_infrastructure/lib/aws/monitoring_helper.py
Labels: enhancement, Needs Review, Monitoring and Alerting, Open edX, product:infrastructure

#1851 Md/issue 1841
  src/bilder/images/airbyte/deploy.py
  src/bridge/lib/versions.py
  src/ol_infrastructure/applications/airbyte/__main__.py
Labels: bug, enhancement, Data, DevOps, Needs Review

#1854 Updated the rds writelatency cloudwatch alarm to be less sensitive.
  src/ol_infrastructure/components/aws/database.py
Labels: Monitoring and Alerting

#1860 1856: Add fake touchstone and okta in CI and QA
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.CI.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: Needs Review

#1873 REGISTRATION_VALIDATION_RATELIMIT for xPro
  src/bilder/components/caddy/steps.py
  src/bilder/components/hashicorp/consul/models.py
  src/bilder/components/hashicorp/consul_esm/models.py
  src/bilder/components/hashicorp/consul_template/models.py
  src/bilder/components/hashicorp/steps.py
  src/bilder/components/hashicorp/vault/models.py
  src/bilder/components/tika/models.py
  src/bilder/components/traefik/steps.py
  src/bilder/images/concourse/deploy.py
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/lms_only.yml.tmpl
  src/ol_concourse/pipelines/infrastructure/grafana_cloud/pipeline.py
  src/ol_concourse/pipelines/infrastructure/keycloak/docker_packer_pulumi_pipeline.py
  src/ol_concourse/pipelines/open_edx/codejail/docker_packer_pulumi_pipeline.py
  src/ol_concourse/pipelines/open_edx/edx_notes/docker_packer_pulumi_pipeline.py
  src/ol_concourse/pipelines/open_edx/edx_platform/meta.py
  src/ol_concourse/pipelines/open_edx/edx_platform/packer_pulumi_pipeline.py
  src/ol_concourse/pipelines/open_edx/forum/meta.py
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
  src/ol_concourse/pipelines/open_edx/tubular/tubular.py
  src/ol_infrastructure/applications/airbyte/__main__.py
  src/ol_infrastructure/applications/codejail/__main__.py
  src/ol_infrastructure/applications/concourse/__main__.py
  src/ol_infrastructure/applications/dagster/__main__.py
  src/ol_infrastructure/applications/edx_notes/__main__.py
  src/ol_infrastructure/applications/edxapp/__main__.py
  src/ol_infrastructure/applications/forum/__main__.py
  src/ol_infrastructure/applications/keycloak/__main__.py
  src/ol_infrastructure/applications/ocw_site/__main__.py
  src/ol_infrastructure/applications/ocw_studio/__main__.py
  src/ol_infrastructure/applications/odl_video_service/__main__.py
  src/ol_infrastructure/applications/redash/__main__.py
  src/ol_infrastructure/applications/tika/__main__.py
  src/ol_infrastructure/applications/xqueue/__main__.py
  src/ol_infrastructure/components/aws/cache.py
  src/ol_infrastructure/components/aws/database.py
  src/ol_infrastructure/components/services/vault.py
  src/ol_infrastructure/infrastructure/aws/data_warehouse/__main__.py
  src/ol_infrastructure/infrastructure/aws/opensearch/__main__.py
  src/ol_infrastructure/infrastructure/consul/__main__.py
  src/ol_infrastructure/infrastructure/vault/__main__.py
  src/ol_infrastructure/infrastructure/vector_log_proxy/__main__.py
  src/ol_infrastructure/lib/consul.py
  src/ol_infrastructure/lib/vault.py
Labels: Open edX, xPRO, product:xpro

#1887 Postmortem for xpro outage
  docs/post-mortems/20231030_xpro_outage.md
Labels: documentation, Monitoring and Alerting

#1888 Giving mitxonline edxapp workers dedicated CPU
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.Production.yaml
  src/ol_infrastructure/applications/edxapp/__main__.py
Labels: Infrastructure
