Repository mitodl/ol-infrastructure, pull requests merged in 2023-08, with the labels that each got.

#1660 version: Update Debian references to Bookworm (v12)
  Vagrantfile
  copier_templates/pyinfra_component/{{ _copier_answers.component_name }}/packer.pkr.hcl.jinja
  dockerfiles/openedx-forum/Dockerfile
  dockerfiles/vdist_debian
  pipelines/ocw/ocw-to-hugo.yml
  src/bilder/components/caddy/packer.pkr.hcl
  src/bilder/components/concourse/packer.pkr.hcl
  src/bilder/components/docker/packer.pkr.hcl
  src/bilder/components/traefik/packer.pkr.hcl
  src/bilder/components/vector/packer.pkr.hcl
  src/bilder/images/airbyte/airbyte.pkr.hcl
  src/bilder/images/codejail/codejail.pkr.hcl
  src/bilder/images/dagster/dagster.pkr.hcl
  src/bilder/images/edx_notes/edx_notes.pkr.hcl
  src/bilder/images/forum/forum.pkr.hcl
  src/bilder/images/keycloak/keycloak.pkr.hcl
  src/bilder/images/odl_video_service/odl_video_service.pkr.hcl
  src/bilder/images/packer.pkr.hcl
  src/bilder/images/redash/redash.pkr.hcl
  src/bilder/images/xqueue/xqueue.pkr.hcl
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Maintenance, Infrastructure

#1662 ocw_studio issue 1874
  src/ol_infrastructure/applications/ocw_studio/__main__.py
Labels: bug, DevOps, Needs Review, OCW

#1658 Renamed mit_open stacks to open_discussions / New stacks for mit-open
  src/bridge/secrets/opensearch/opensearch.mitopen.ci.yaml
  src/bridge/secrets/opensearch/opensearch.mitopen.production.yaml
  src/bridge/secrets/opensearch/opensearch.mitopen.qa.yaml
  src/ol_infrastructure/applications/mit_open/Pulumi.applications.mitopen.CI.yaml
  src/ol_infrastructure/applications/mit_open/Pulumi.applications.mitopen.Production.yaml
  src/ol_infrastructure/applications/mit_open/Pulumi.applications.mitopen.QA.yaml
  src/ol_infrastructure/applications/mit_open/Pulumi.yaml
  src/ol_infrastructure/applications/mit_open/__main__.py
  src/ol_infrastructure/applications/open_discussions/BUILD
  src/ol_infrastructure/applications/open_discussions/Pulumi.applications.open_discussions.CI.yaml
  src/ol_infrastructure/applications/open_discussions/Pulumi.applications.open_discussions.Production.yaml
  src/ol_infrastructure/applications/open_discussions/Pulumi.applications.open_discussions.QA.yaml
  src/ol_infrastructure/applications/open_discussions/Pulumi.yaml
  src/ol_infrastructure/applications/open_discussions/__init__.py
  src/ol_infrastructure/applications/open_discussions/__main__.py
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitopen.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitopen.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitopen.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/__main__.py
Labels: DevOps, InProgress

#1641 Replacing pomerium with traefik
  src/bilder/images/airbyte/deploy.py
  src/bilder/images/airbyte/files/.env_traefik_forward_auth.tmpl
  src/bilder/images/airbyte/files/docker-compose.yaml
  src/bilder/images/airbyte/files/nginx_htpasswd.tmpl
  src/bilder/images/airbyte/files/nginx_pomerium.conf.tmpl
  src/bilder/images/airbyte/files/nginx_proxy.conf
  src/bilder/images/airbyte/templates/.env.tmpl
  src/bridge/lib/versions.py
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#1642 feat: set COURSES_INVITE_ONLY to true
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#1681 proctortrack troubleshooting changes
  dockerfiles/openedx-edxapp/pip_package_lists/master/mitxonline.txt
  dockerfiles/openedx-edxapp/settings/lms/assets.not_py
Labels: DevOps, MITx Online, Open edX

#1682 Vault mount + secrets for MIT Open
  src/bridge/secrets/mitopen/secrets.ci.yaml
  src/bridge/secrets/mitopen/secrets.production.yaml
  src/bridge/secrets/mitopen/secrets.qa.yaml
  src/ol_infrastructure/applications/mit_open/__main__.py
Labels: DevOps, Needs Review, product:mit-open

#1685 use_docker: true for mitxonline-production
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.Production.yaml
Labels: DevOps, MITx Online

#1688 feat: set COURSES_INVITE_ONLY to true #2
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review, Open edX, product:mitx-online

#1687 Keycloak config for MIT Open
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#1689 Md/mit open config r2
  src/bridge/secrets/mitopen/secrets.ci.yaml
  src/ol_infrastructure/applications/mit_open/Pulumi.applications.mitopen.CI.yaml
  src/ol_infrastructure/applications/mitopen/BUILD
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.Production.yaml
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.QA.yaml
  src/ol_infrastructure/applications/mitopen/Pulumi.yaml
  src/ol_infrastructure/applications/mitopen/__init__.py
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: DevOps, product:mit-open

#1690 Install cron on vault servers with Debian 12.1
  src/bilder/images/vault/deploy.py
Labels: bug, DevOps, Infrastructure

#1667 feat: allow bulk retirement API url
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#1675 Updating redirects for 9.00SC
  src/ol_infrastructure/applications/ocw_site/redirect_dict.json
Labels: Waiting on Author

#1691 Fix DummyVarSource in ol-concourse
  src/ol_concourse/lib/models/pipeline.py
Labels: Needs Review, product:infrastructure

#1693 revert: certificate html view setting in Studio
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Waiting on Author

#1692 Updating redirects for 9.00SC
  src/ol_infrastructure/applications/ocw_site/redirect_dict.json
Labels: Needs Review

#1703 md5 passwords for mit open database users
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: bug, DevOps

#1706 Update redirect for heavy metal course
  src/ol_infrastructure/applications/ocw_site/redirect_dict.json
Labels: Needs Review

#1708 Config reconcile for edxapp dockerization
  src/bilder/images/edxapp_v2/templates/edxapp/mitx/lms_only.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/reconcile_configs.sh
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/common_values.yml.tmpl
Labels: DevOps, Needs Review, Open edX

#1710 Change Value class in ol-concourse to a type of Any instead of str
  src/ol_concourse/BUILD
  src/ol_concourse/lib/models/pipeline.py
Labels: Needs Review

#1711 Add 19.785 2019 redirect to 2021
  src/ol_infrastructure/applications/ocw_site/redirect_dict.json
Labels: Needs Review, OCW

#1719 Keycloak CI OpenID client for local testing
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.CI.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#1695 Misc Stuff
  src/bilder/components/vector/steps.py
  src/bilder/components/vector/templates/host_metrics.yaml
  src/bilder/images/airbyte/airbyte.pkr.hcl
  src/bilder/images/codejail/codejail.pkr.hcl
  src/bilder/images/dagster/dagster.pkr.hcl
  src/bilder/images/edx_notes/edx_notes.pkr.hcl
  src/bilder/images/forum/forum.pkr.hcl
  src/bilder/images/keycloak/keycloak.pkr.hcl
  src/bilder/images/odl_video_service/odl_video_service.pkr.hcl
  src/bilder/images/packer.pkr.hcl
  src/bilder/images/redash/redash.pkr.hcl
  src/bilder/images/xqueue/xqueue.pkr.hcl
  src/ol_infrastructure/applications/airbyte/__main__.py
  src/ol_infrastructure/applications/codejail/__main__.py
  src/ol_infrastructure/applications/concourse/Pulumi.applications.concourse.Production.yaml
  src/ol_infrastructure/applications/concourse/__main__.py
  src/ol_infrastructure/applications/dagster/__main__.py
  src/ol_infrastructure/applications/edx_notes/__main__.py
  src/ol_infrastructure/applications/edxapp/__main__.py
  src/ol_infrastructure/applications/forum/__main__.py
  src/ol_infrastructure/applications/keycloak/__main__.py
  src/ol_infrastructure/applications/odl_video_service/__main__.py
  src/ol_infrastructure/applications/redash/__main__.py
  src/ol_infrastructure/applications/xqueue/__main__.py
  src/ol_infrastructure/infrastructure/consul/__main__.py
  src/ol_infrastructure/infrastructure/vault/__main__.py
  src/ol_infrastructure/infrastructure/vector_log_proxy/__main__.py
Labels: enhancement, DevOps, Needs Review, Monitoring and Alerting

#1720 Tweaks to fix touchstone idp
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#1727 Created consul cluster in the data_vpc in CI.
  src/ol_infrastructure/infrastructure/consul/Pulumi.infrastructure.consul.data.CI.yaml
Labels: DevOps, Infrastructure
