Repository mitodl/ol-infrastructure, pull requests merged in 2023-06, with the labels that each got.

#1545 config: enable email scheduling in communications MFE (MITxOnline)
  src/concourse/pipelines/open_edx/mfe/pipeline.py
  src/concourse/pipelines/open_edx/mfe/values.py
Labels: Needs Review

#1547 fix ocw redirect urls
  src/ol_infrastructure/applications/ocw_site/redirect_dict.json
Labels: Needs Review

#1558 First pass at traefik/dagster config
  src/bilder/images/dagster/deploy.py
  src/bilder/images/dagster/files/.env_traefik_forward_auth.tmpl
  src/bilder/images/dagster/files/htpasswd.tmpl
  src/bilder/images/dagster/files/nginx.conf.tmpl
  src/bilder/images/dagster/files/traefik.conf.tmpl
  src/bilder/images/dagster/templates/docker-compose.yaml.j2
Labels: DevOps

#1563 Added a basic keyloak/dagster client
  src/ol_infrastructure/applications/keycloak/Pulumi.applications.keycloak.CI.yaml
  src/ol_infrastructure/applications/keycloak/Pulumi.applications.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#1561 Upgrade MIT Open OpenSearch clusters to OS 1.3
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open.QA.yaml
Labels: Infrastructure, InProgress, product:mit-open

#1566 Initial pass at adding production deployment for keycloak
  src/bridge/secrets/keycloak/data.production.yaml
  src/ol_infrastructure/applications/keycloak/Pulumi.applications.keycloak.Production.yaml
  src/ol_infrastructure/applications/keycloak/__main__.py
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
Labels: DevOps

#1570 Concourse EBS enhancements
  src/ol_infrastructure/applications/concourse/Pulumi.applications.concourse.CI.yaml
  src/ol_infrastructure/applications/concourse/Pulumi.applications.concourse.Production.yaml
  src/ol_infrastructure/applications/concourse/Pulumi.applications.concourse.QA.yaml
  src/ol_infrastructure/applications/concourse/__main__.py
Labels: enhancement, DevOps, Infrastructure, OCW

#1572 Minor fixes to vault service file
  src/bilder/components/hashicorp/templates/vault.service.j2
Labels: enhancement, DevOps

#1574 Minor fixes to docker-compose service
  src/bilder/components/baseline/templates/systemd_file_watcher.path.j2
  src/bilder/components/docker/steps.py
Labels: DevOps

#1576 Fix error deleting read_replica
  src/ol_infrastructure/components/aws/database.py
Labels: DevOps

#1589 Enabling the email scheduling in the MFE for MITX and MITX-STAGING
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: enhancement, product:residential

#1567 config: override brand for learner dashboard MFE in MITxOnline QA
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Needs Review

#1601 setup a cronjob for "process scheduled instructor tasks"
  src/bilder/images/edxapp/deploy.py
  src/bilder/images/edxapp/files/process_scheduled_instructor_tasks
Labels: enhancement, DevOps, Needs Review, MITx Online, Open edX

#1590 feat: enable mktg site
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review
