Repository mitodl/ol-infrastructure, pull requests merged in 2023-07, with the labels that each got.

#1626 Issue 1571 , ocw-preview.odl.mit.edu -> live
  src/ol_infrastructure/applications/ocw_site/Pulumi.applications.ocw_site.Production.yaml
Labels: DevOps, Needs Review, OCW

#1632 Concourse monitoring improvements
  src/bilder/images/concourse/deploy.py
  src/ol_infrastructure/applications/concourse/__main__.py
Labels: DevOps, Monitoring and Alerting

#1639 config: enable certificate_html_view to enable certificate option in studio (MITxOnline)
  src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/ol_infrastructure/infrastructure/aws/network/__main__.py
Labels: Needs Review

#1650 Enabling scheduled emails in MITXOnline Production.
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: DevOps, MITx Online, product:mitx-online

#1652 Render ol_concourse pipelines by alias
  src/bilder/components/hashicorp/consul/models.py
  src/ol_concourse/lib/models/pipeline.py
Labels: bug, DevOps

#1656 Added specific version of edx-proctoring-proctortrack
  src/bilder/images/edxapp/group_data/all.py
Labels: DevOps, Open edX
