Repository mitodl/ol-infrastructure, pull requests merged in 2023-12, with the labels that each got.

#1967 Add keycloak ratelimit though traefik
  src/bilder/images/keycloak/files/docker-compose.yaml
Labels: DevOps

#1970 Add SCIM spi to keycloak build
  src/ol_concourse/pipelines/infrastructure/keycloak/docker_packer_pulumi_pipeline.py
Labels: DevOps

#1969 config: set Zendesk contact URLs for MIT xPRO and MITx Online
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/common_values.yml.tmpl
Labels: Needs Review

#1966 Upgrades mitopen opensearch clusters to 2.11
  src/bridge/secrets/mitopen/secrets.production.yaml
  src/bridge/secrets/mitopen/secrets.qa.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitopen.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitopen.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitopen.QA.yaml
Labels: enhancement, DevOps, Maintenance, Infrastructure, do not merge, product:mit-open

#1978 fix: fix learning mfe base url
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Needs Review

#1971 Deploy superset
  src/bilder/images/superset/README.md
  src/bilder/images/superset/__init__.py
  src/bilder/images/superset/deploy.py
  src/bilder/images/superset/files/docker-compose.yaml
  src/bilder/images/superset/files/vector/superset_logs.yaml
  src/bilder/images/superset/superset.pkr.hcl
  src/bridge/secrets/superset/data.ci.yaml
  src/bridge/secrets/superset/data.production.yaml
  src/bridge/secrets/superset/data.qa.yaml
  src/ol_concourse/pipelines/infrastructure/superset/__init__.py
  src/ol_concourse/pipelines/infrastructure/superset/docker_packer_pulumi_pipeline.py
  src/ol_infrastructure/applications/edxapp/__main__.py
  src/ol_infrastructure/applications/superset/Pulumi.applications.superset.CI.yaml
  src/ol_infrastructure/applications/superset/Pulumi.applications.superset.Production.yaml
  src/ol_infrastructure/applications/superset/Pulumi.applications.superset.QA.yaml
  src/ol_infrastructure/applications/superset/Pulumi.yaml
  src/ol_infrastructure/applications/superset/__init__.py
  src/ol_infrastructure/applications/superset/__main__.py
  src/ol_infrastructure/applications/superset/superset_server_policy.hcl
  src/ol_infrastructure/components/aws/auto_scale_group.py
  src/ol_infrastructure/infrastructure/aws/policies/__main__.py
  src/ol_infrastructure/lib/aws/route53_helper.py
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.CI.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/vault/static_mounts/Pulumi.substructure.vault.static_mounts.CI.yaml
  src/ol_infrastructure/substructure/vault/static_mounts/Pulumi.substructure.vault.static_mounts.Production.yaml
  src/ol_infrastructure/substructure/vault/static_mounts/Pulumi.substructure.vault.static_mounts.QA.yaml
  src/ol_infrastructure/substructure/vault/static_mounts/Pulumi.yaml
  src/ol_infrastructure/substructure/vault/static_mounts/__init__.py
  src/ol_infrastructure/substructure/vault/static_mounts/__main__.py
  src/ol_superset/Dockerfile
  src/ol_superset/docker-compose.yaml
  src/ol_superset/pythonpath/auth/__init__.py
  src/ol_superset/pythonpath/auth/keycloak.py
  src/ol_superset/pythonpath/superset_config.py
  src/ol_superset/pythonpath/vault/__init__.py
  src/ol_superset/pythonpath/vault/aws_auth.py
  src/ol_superset/requirements.in
  src/ol_superset/requirements.txt
Labels: Data, product:data-platform, product:infrastructure

#1975 Managing the tika/access-token value in vault
  src/ol_infrastructure/applications/tika/__main__.py
Labels: bug, DevOps, Needs Review, product:mit-open

#2014 Fixing themes on earthly builds.
  dockerfiles/openedx-edxapp/Earthfile
Labels: bug, DevOps, Open edX

#2015 Switch all lower environments to earthly.
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.QA.yaml
Labels: DevOps, Open edX

#2020 fix: add MIT canvas URL in CORS_ORIGIN_WHITELIST
  src/bilder/images/edxapp_v2/templates/edxapp/mitx-staging/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitx/common_values.yml.tmpl
Labels: Needs Review

#1961 Reconciled all waffle flags for edxapp deployments.
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.QA.yaml
  src/ol_infrastructure/applications/edxapp/__main__.py
Labels: enhancement, DevOps, do not merge

#2027 Revert "Revert "Revert "Revert "feat: set COURSES_INVITE_ONLY to true""""
  src/bilder/components/hashicorp/consul_template/steps.py
  src/bilder/images/edxapp/templates/edxapp/xpro/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/common_values.yml.tmpl
Labels: Needs Review, do not merge
