Repository mitodl/ol-infrastructure, pull requests merged in 2023-11, with the labels that each got.

#1899 concourse sg fix
  src/ol_infrastructure/applications/concourse/__main__.py
Labels: bug, DevOps

#1902 Point to new keycloak customization repo
  src/ol_concourse/pipelines/infrastructure/keycloak/docker_packer_pulumi_pipeline.py
Labels: DevOps

#1905 Create registration workflow
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#1913 Add custom browser flow to olapps realm
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: Needs Review

#1924 Updated some keycloak prod values
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
Labels: DevOps

#1933 Add actionlint to pre-commit
  .pre-commit-config.yaml
Labels: DevOps

#1932 config: disable feedback widget
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: Needs Review

#1857 Add cache control headers for OCW
  src/ol_infrastructure/applications/ocw_site/snippets/ttl_setup.vcl
Labels: Needs Review

#1942 Adding * to allowed CORS headers for OCW.
  src/ol_infrastructure/applications/ocw_site/__main__.py
Labels: DevOps, OCW

#1946 Framework tagging enhancements for edxapp images
  src/bilder/images/edxapp_v2/custom_install.pkr.hcl
  src/ol_concourse/pipelines/open_edx/edx_platform_v2/grouped_docker_packer_pulumi_pipeline.py
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.QA.yaml
  src/ol_infrastructure/applications/edxapp/__main__.py
Labels: enhancement, Needs Review, Open edX
