Repository mitodl/ol-infrastructure, pull requests merged in 2024-10, with the labels that each got.

#2696 Switch to using ol-mitlearn-client
  src/ol_infrastructure/applications/mitlearn/__main__.py
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#2697 Point to correct learn secret
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: DevOps

#2698 Fix argument casing typo
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: Needs Review

#2701 Make first/last names optional
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: Needs Review

#2593 Pulumi RDS, Consul, k8s and supporting infra for OpenMetaData CI
  src/bridge/lib/versions.py
  src/ol_infrastructure/applications/open_metadata/Pulumi.applications.open_metadata.CI.yaml
  src/ol_infrastructure/applications/open_metadata/Pulumi.yaml
  src/ol_infrastructure/applications/open_metadata/__init__.py
  src/ol_infrastructure/applications/open_metadata/__main__.py
  src/ol_infrastructure/applications/open_metadata/open_metadata_policy.hcl
  src/ol_infrastructure/components/services/vault.py
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open_metadata.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open_metadata.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open_metadata.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/__main__.py
  src/ol_infrastructure/lib/aws/eks_helper.py
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.CI.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: enhancement, DevOps, Needs Review, Infrastructure, product:data-platform

#2702 IAM adjustments for EKS clusters
  src/ol_infrastructure/applications/concourse/__main__.py
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/infrastructure/aws/iam/__main__.py
Labels: enhancement, DevOps, Infrastructure

#2706 feat: scheduling daily digest command to run every midnight UTC
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#2717 Md/vault secrets operator transit encryption
  src/ol_infrastructure/applications/open_metadata/open_metadata_policy.hcl
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/infrastructure/aws/eks/vso_transit_policy.hcl
  src/ol_infrastructure/substructure/vault/encryption_mounts/__main__.py
Labels: enhancement, DevOps, Infrastructure

#2712 Md/eks vault component resources
  src/ol_infrastructure/applications/open_metadata/__main__.py
  src/ol_infrastructure/components/aws/olvpc.py
  src/ol_infrastructure/components/services/vault.py
  src/ol_infrastructure/substructure/aws/eks/__main__.py
  src/ol_infrastructure/substructure/aws/eks/traefik_vault_policy.hcl
Labels: enhancement, DevOps, Infrastructure, Design

#2722 Duplicate open-api-clients build pipeline for Unified Ecommerce
  src/ol_concourse/pipelines/libraries/scripts/unified-ecommerce-api-clients-bumpver.sh
  src/ol_concourse/pipelines/libraries/scripts/unified-ecommerce-api-clients-commit-changes.sh
  src/ol_concourse/pipelines/libraries/scripts/unified-ecommerce-api-clients-publish-node.sh
  src/ol_concourse/pipelines/libraries/scripts/unified-ecommerce-api-clients-tag-release.sh
  src/ol_concourse/pipelines/libraries/unified_ecommerce_api_clients.py
Labels: Needs Review

#2732 fix: celery beat schedule name in edx
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#2739 Add scim license key for Keycloak CI
  src/bridge/secrets/keycloak/data.ci.yaml
Labels: DevOps

#2745 fix: typo in daily digest celery schedule
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#2746 add metrics-server to eks deployments.
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
Labels: enhancement, DevOps, Infrastructure

#2713 Add email optin attribute and protocol mappers to ol apps keycloak config
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#2757 Added configuration for keycloak client scopes
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: Needs Review

#2750 Adjust Keycloak pipeline for new SCIM client
  src/bilder/images/keycloak/files/.env.tmpl
  src/bridge/secrets/keycloak/data.ci.yaml
  src/ol_concourse/pipelines/infrastructure/keycloak/docker_packer_pulumi_pipeline.py
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#2759 Md/gateway improvements
  src/ol_infrastructure/applications/open_metadata/__main__.py
  src/ol_infrastructure/components/aws/eks.py
Labels: enhancement, DevOps

#2760 Remove MITPE_BASE_API_URL setting, add MITPE_API_ENABLED=True for RC (mit-learn)
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: Needs Review

#2765 allow concourse to deploy EKS resources
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
Labels: bug, DevOps
