Repository mitodl/ol-infrastructure, pull requests merged in 2024-07, with the labels that each got.

#2522 Md/issue 2518 - Concourse
  src/ol_infrastructure/applications/concourse/__main__.py
  src/ol_infrastructure/applications/edx_notes/__main__.py
  src/ol_infrastructure/components/aws/auto_scale_group.py
Labels: DevOps, Needs Review, Infrastructure, Tech Debt

#2525 Md/issue 2518 - Consul
  src/ol_infrastructure/infrastructure/consul/__main__.py
Labels: enhancement, DevOps, Needs Review, Infrastructure, Tech Debt

#2545 feat: enable email daily digests in mitxonline qa
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
Labels: Needs Review

#2549 feat(xpro): turn on FEATURE_ENABLE_EXTERNAL_COURSE_SYNC
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.Production.yaml
Labels: Needs Review

#2550 Resolves Issue 4867
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#2553 fix: add learning MFE branding overrides
  src/bridge/settings/openedx/version_matrix.py
Labels: Needs Review

#2554 remove paver steps from edxapp builds
  dockerfiles/openedx-edxapp/Earthfile
Labels: enhancement, DevOps, Maintenance, do not merge, Open edX

#2527 md/issue 2518 - Vault
  src/ol_infrastructure/infrastructure/vault/__main__.py
Labels: do not merge

#2566 fix: airbyte filesize fix
  src/bilder/images/airbyte/deploy.py
  src/bilder/images/airbyte/files/docker-compose.yaml
  src/bilder/images/airbyte/files/dynamic_config_development.yaml
Labels: bug, Data, DevOps

#2564 Turn on discussions.pages_and_resources_mfe waffle flag for everyone
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
Labels: Needs Review

#2568 Strip MITOpen cookies from requests routed to s3
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: bug, DevOps

#2578 Updated cybersource bootcamps qa creds
  src/bridge/secrets/bootcamps/secrets.qa.yaml
Labels: DevOps
