Repository mitodl/ol-infrastructure, pull requests merged in 2024-03, with the labels that each got.

#2241 Add YOUTUBE_CONFIG_URL setting for mitopen
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: Waiting on Author

#2244 fix mitopen 'app' database role
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: enhancement, DevOps, product:mit-open

#2248 micromasters heroku var management
  src/ol_infrastructure/applications/micromasters/Pulumi.applications.micromasters.CI.yaml
  src/ol_infrastructure/applications/micromasters/Pulumi.applications.micromasters.Production.yaml
  src/ol_infrastructure/applications/micromasters/Pulumi.applications.micromasters.QA.yaml
  src/ol_infrastructure/applications/micromasters/__main__.py
Labels: enhancement, DevOps, SaltStack Deprecation, product:micromasters

#2173 issue 2074 - mitxonline
  src/ol_infrastructure/applications/mitxonline/Pulumi.applications.mitxonline.Production.yaml
  src/ol_infrastructure/applications/mitxonline/Pulumi.applications.mitxonline.QA.yaml
  src/ol_infrastructure/applications/mitxonline/__main__.py
Labels: DevOps, Needs Review, SaltStack Deprecation, product:mitx-online

#2262 Redirect mitx-courses-on-edx.htm to openlearning URL
  src/ol_infrastructure/applications/ocw_site/redirect_dict.json
Labels: Needs Review

#2283 config: Update xPRO production logo URLs
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: Needs Review

#2286 config: Use self hosted logos (xPRO)
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/common_values.yml.tmpl
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: Needs Review

#2306 feat: add ZENDESK_HELP_WIDGET_KEY
  src/ol_infrastructure/applications/xpro/__main__.py
Labels: Needs Review

#2305 Expanding vector env var fix to all application stacks
  src/ol_infrastructure/applications/airbyte/__main__.py
  src/ol_infrastructure/applications/apisix/__main__.py
  src/ol_infrastructure/applications/celery_monitoring/__main__.py
  src/ol_infrastructure/applications/codejail/__main__.py
  src/ol_infrastructure/applications/concourse/__main__.py
  src/ol_infrastructure/applications/dagster/__main__.py
  src/ol_infrastructure/applications/edx_notes/__main__.py
  src/ol_infrastructure/applications/edxapp/__main__.py
  src/ol_infrastructure/applications/forum/__main__.py
  src/ol_infrastructure/applications/keycloak/__main__.py
  src/ol_infrastructure/applications/odl_video_service/__main__.py
  src/ol_infrastructure/applications/redash/__main__.py
  src/ol_infrastructure/applications/superset/__main__.py
  src/ol_infrastructure/applications/tika/__main__.py
  src/ol_infrastructure/applications/xqueue/__main__.py
  src/ol_infrastructure/infrastructure/consul/__main__.py
  src/ol_infrastructure/infrastructure/vault/__main__.py
Labels: bug, DevOps, Needs Review

#2310 config: enable zendesk help widget (xPRO Production)
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.Production.yaml
Labels: Needs Review

#2270 feat: update mitx logo configs
  src/bilder/images/edxapp_v2/templates/edxapp/mitx-staging/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitx/common_values.yml.tmpl
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: Needs Review

#2308 fix: update config to avoid logo leak to production
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: Needs Review

#2309 packer pulumi pipeline for apisix
  src/ol_concourse/pipelines/infrastructure/apisix/BUILD
  src/ol_concourse/pipelines/infrastructure/apisix/__init__.py
  src/ol_concourse/pipelines/infrastructure/apisix/packer_pulumi_pipeline.py
Labels: DevOps
