Repository mitodl/ol-infrastructure, pull requests merged in 2024-09, with the labels that each got.

#2651 Added settings for sentry traces/profiles on learn
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
Labels: Needs Review

#2660 Add EDX_PROGRAMS_API_URL setting for mit learn
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: Needs Review

#2665 set MITOL_NOINDEX var in mit-learn environments
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
Labels: Needs Review, product:infrastructure

#2669 Adding a missing export to the DNS stack
  src/ol_infrastructure/infrastructure/aws/dns/__main__.py
Labels: bug, DevOps

#2674 hotfix mitxonline xqueue creds
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: bug, DevOps

#2664 Md/k8s cleanup
  .pre-commit-config.yaml
  src/bridge/lib/magic_numbers.py
  src/ol_concourse/pipelines/infrastructure/aws/pulumi_pipeline.py
  src/ol_infrastructure/components/aws/olvpc.py
  src/ol_infrastructure/infrastructure/aws/eks/KUBE_CONFIG_SETUP.md
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.operations.CI.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.operations.CI.yaml_bak
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/infrastructure/aws/eks/files/aws_load_balancer_config_iam_policy.json
  src/ol_infrastructure/infrastructure/aws/eks/files/omd_d_values.yaml
  src/ol_infrastructure/infrastructure/aws/eks/files/omd_notes.txt
  src/ol_infrastructure/infrastructure/aws/eks/files/omd_values.yaml
  src/ol_infrastructure/infrastructure/aws/iam/Pulumi.infrastructure.aws.iam.yaml
  src/ol_infrastructure/infrastructure/aws/iam/Pulumi.yaml
  src/ol_infrastructure/infrastructure/aws/iam/__init__.py
  src/ol_infrastructure/infrastructure/aws/iam/__main__.py
  src/ol_infrastructure/lib/aws/iam_helper.py
Labels: enhancement, DevOps, Infrastructure

#2684 *.odl.mit.edu key and cert formatting additions
  src/bridge/secrets/vault/secrets.ci.yaml
  src/bridge/secrets/vault/secrets.production.yaml
  src/bridge/secrets/vault/secrets.qa.yaml
Labels: enhancement, DevOps

#2693 SCIM config and disable keycloakify
  src/ol_concourse/pipelines/infrastructure/keycloak/docker_packer_pulumi_pipeline.py
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps
