Repository mitodl/ol-infrastructure, pull requests merged in 2024-04, with the labels that each got.

#1373 AWS OVS CI environment
  src/bilder/images/odl_video_service/odl_video_service.pkr.hcl
  src/ol_concourse/lib/jobs/infrastructure.py
  src/ol_concourse/pipelines/infrastructure/ovs/docker_packer_pulumi_pipeline.py
  src/ol_infrastructure/applications/odl_video_service/Pulumi.applications.odl_video_service.CI.yaml
  src/ol_infrastructure/applications/odl_video_service/Pulumi.applications.odl_video_service.Production.yaml
  src/ol_infrastructure/applications/odl_video_service/Pulumi.applications.odl_video_service.QA.yaml
  src/ol_infrastructure/applications/odl_video_service/__main__.py
Labels: DevOps, Tech Debt, product:infrastructure

#2320 config: Update Zendesk chat widget key
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.CI.yaml
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.Production.yaml
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.QA.yaml
  src/ol_infrastructure/applications/xpro/__main__.py
Labels: Needs Review

#2323 Configure olapps to use the ol email theme
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: Needs Review

#2321 issue 2074 - open_discussions
  src/ol_infrastructure/applications/open_discussions/Pulumi.applications.open_discussions.Production.yaml
  src/ol_infrastructure/applications/open_discussions/Pulumi.applications.open_discussions.QA.yaml
  src/ol_infrastructure/applications/open_discussions/__main__.py
Labels: DevOps, Needs Review, SaltStack Deprecation, product:mit-open

#2337 config: enable daily digest (MITx Online)
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#2327 Use external prod urls wherever feasible
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.Production.yaml
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.QA.yaml
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: Needs Review

#2345 Adds PostHog-specific settings to the MIT Open config
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.Production.yaml
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.QA.yaml
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: DevOps, Needs Review, product:mit-open

#2371 Set correct URL for MIT Open production
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.Production.yaml
Labels: Needs Review

#2375 config: enable blake2b hashing (MITxOnline)
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: work in progress

#2386 fix: fixed the discussion sidebar issue
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
Labels: Needs Review

#2383 Removing no longer needed migration plugin
  src/ol_concourse/pipelines/infrastructure/keycloak/docker_packer_pulumi_pipeline.py
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps
