Repository mitodl/ol-infrastructure, pull requests merged in 2024-02, with the labels that each got.

#2135 config: update logo URLs for xPRO
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: Waiting on Author

#2132 Md/issue 2074 - xpro
  src/bridge/secrets/xpro/secrets.ci.yaml
  src/bridge/secrets/xpro/secrets.production.yaml
  src/bridge/secrets/xpro/secrets.qa.yaml
  src/ol_concourse/pipelines/infrastructure/xpro/__init__.py
  src/ol_concourse/pipelines/infrastructure/xpro/pipeline.py
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.CI.yaml
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.Production.yaml
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.QA.yaml
  src/ol_infrastructure/applications/xpro/__main__.py
Labels: DevOps, SaltStack Deprecation, work in progress, product:xpro

#2138 feat: disable authoring MFE app help URLs
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/cms_only.yml.tmpl
Labels: Waiting on Author

#2137 feat: add learning base url
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Waiting on Author

#2159 config: add logo_url and trademark_logo_url for platform (xPRO)
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/common_values.yml.tmpl
Labels: Needs Review

#2161 mitxonline webpack.json fix
  src/bilder/images/edxapp_v2/deploy.py
Labels: bug, Needs Review, MITx Online, Open edX, Time Sensitive, product:mitx-online, product:xpro

#2160 Md/issue 2074 bootcamps
  pyproject.toml
  src/bridge/secrets/bootcamps/secrets.production.yaml
  src/bridge/secrets/bootcamps/secrets.qa.yaml
  src/ol_infrastructure/applications/bootcamps/Pulumi.applications.bootcamps.Production.yaml
  src/ol_infrastructure/applications/bootcamps/Pulumi.applications.bootcamps.QA.yaml
  src/ol_infrastructure/applications/bootcamps/__main__.py
Labels: DevOps, SaltStack Deprecation, product:bootcamps

#2169 Adding setting for mit-open SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.Production.yaml
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.QA.yaml
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: Needs Review

#2170 add rc ocw to open next prod cors
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.Production.yaml
Labels: product:mit-open

#2171 safe waffles 🧇
  src/bilder/images/edxapp_v2/files/docker-compose.yaml.tmpl
Labels: bug, Open edX

#2172 Removed renamed/unused flag EMAIL_USE_DEFAULT_FROM_FOR_BULK
  src/bilder/images/edxapp_v2/templates/edxapp/mitx-staging/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitx/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/common_values.yml.tmpl
Labels: Waiting on Author

#2162 Concourse publishing pipeline for open-api-clients
  src/ol_concourse/pipelines/libraries/__init__.py
  src/ol_concourse/pipelines/libraries/open_api_clients.py
  src/ol_concourse/pipelines/libraries/scripts/open-api-clients-bumpver.sh
  src/ol_concourse/pipelines/libraries/scripts/open-api-clients-commit-changes.sh
  src/ol_concourse/pipelines/libraries/scripts/open-api-clients-publish-node.sh
  src/ol_concourse/pipelines/libraries/scripts/open-api-clients-tag-release.sh
Labels: Needs Review

#2192 Add MIT-Open (RC) SCIM configuration
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: Needs Review

#2223 fix: fix default xmodule class name
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/common_values.yml.tmpl
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.QA.yaml
Labels: Needs Review

#2228 Add scim event listener to realm
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: Needs Review
