Repository mitodl/ol-infrastructure, pull requests merged in 2024-05, with the labels that each got.

#2390 config,fix: Resolve disparity in Ruby versions between Quince and Master
  dockerfiles/openedx-forum/Dockerfile
  src/ol_concourse/pipelines/open_edx/forum/docker_packer_pulumi_pipeline.py
Labels: project:open-edx

#2389 config: Use Atlas for managing translation overrides in learning MFE
  src/bridge/settings/openedx/types.py
  src/bridge/settings/openedx/version_matrix.py
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: product:mitx-online, project:open-edx

#2391 config,version: Fix master and Quince edxapp node builds
  dockerfiles/openedx-edxapp/Earthfile
  src/ol_concourse/pipelines/open_edx/edx_platform_v2/earthly_packer_pulumi_pipeline.py
Labels: project:open-edx

#2385 refactor: remove ENABLE_ORDER_RECEIPTS
  src/ol_infrastructure/applications/xpro/__main__.py
Labels: Needs Review

#2403 issue 2343 - grafana health issues
  src/bilder/components/vector/templates/host_metrics.yaml
  src/bilder/images/consul/templates/vector/consul_metrics.yaml
Labels: DevOps, Needs Review, Monitoring and Alerting

#2409 Cleanup old docker code from shared packer configs
  src/bilder/images/packer.pkr.hcl
Labels: DevOps, Maintenance

#2408 issue 2338
  dockerfiles/openedx-edxapp/Dockerfile
  dockerfiles/openedx-edxapp/Earthfile
Labels: bug, DevOps, Needs Review, Open edX, project:open-edx

#2412 Adds `packer fmt` to our precommit configuration
  .pre-commit-config.yaml
  src/bilder/images/xqwatcher/xqwatcher.pkr.hcl
Labels: enhancement, DevOps

#2434 Let MIT Open ingest OLL course data from S3
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: Waiting on Author

#2437 Update posthog env vars
  src/ol_infrastructure/applications/mitxonline/__main__.py
Labels: Needs Review

#2433 static IAM policy and user for gh deployment workflows to s3
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.Production.yaml
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.QA.yaml
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: DevOps, Infrastructure, product:mit-open

#2445 Revert "fix: fixed the discussion sidebar issue"
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
Labels: Waiting on Author

#2452 config: add discussions MFE path, Picked from 2386
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Needs Review

#2455 packer gh ratelimit fix
  src/ol_concourse/lib/jobs/infrastructure.py
Labels: bug

#2456 feat: added waffle flag to hide taxonomies
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
Labels: Needs Review

#2441 MIT Open Application routing paths
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.QA.yaml
Labels: DevOps, Needs Review, product:mit-open

#2457 config: disable Discussions MFE as a default for discussions
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.QA.yaml
Labels: Needs Review

#2458 EMBEDLY_KEY to GH secrets for mit-open
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: DevOps, Needs Review, product:mit-open
