Repository mitodl/ol-infrastructure, pull requests merged in 2024-06, with the labels that each got.

#2459 config: Add S3 backed storage for computed block structures
  src/bilder/images/edxapp_v2/templates/edxapp/mitx-staging/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitx/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/common_values.yml.tmpl
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx-staging.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.CI.yaml
Labels: Waiting on Author

#2471 Change Open URL for login routes
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
Labels: DevOps

#2489 Set YOUTUBE_FETCH_SCHEDULE_SECONDS to 4 hours on both rc and prod mitopen
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: Needs Review

#2429 Issue 2316 - OTEL + ~Airbyte~ Concourse
  src/bilder/components/alloy/__init__.py
  src/bilder/components/alloy/files/config.alloy
  src/bilder/components/alloy/models.py
  src/bilder/components/alloy/steps.py
  src/bilder/images/airbyte/deploy.py
  src/bilder/images/airbyte/files/docker-compose.yaml
  src/bilder/images/airbyte/templates/.env.tmpl
  src/bilder/images/concourse/deploy.py
  src/bridge/secrets/alloy
  src/bridge/secrets/vector/grafana.ci.yaml
  src/bridge/secrets/vector/grafana.production.yaml
  src/bridge/secrets/vector/grafana.qa.yaml
  src/ol_infrastructure/applications/concourse/__main__.py
Labels: enhancement, DevOps, Needs Review, Monitoring and Alerting, product:data-platform

#2481 Reformat some Open key names
  src/bridge/secrets/mitopen/secrets.production.yaml
  src/bridge/secrets/mitopen/secrets.qa.yaml
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: DevOps

#2491 Updated MIT WS certificate for OVS.
  docs/how_to/moira_certificates.md
  src/bridge/secrets/odl_video_service/data.ci.yaml
  src/bridge/secrets/odl_video_service/data.production.yaml
  src/bridge/secrets/odl_video_service/data.qa.yaml
Labels: Time Sensitive, product:ovs

#2492 Add the new user redirect url setting to mit-open
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.Production.yaml
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.QA.yaml
Labels: Needs Review

#2498 Md/issue 2370
  src/bilder/components/hashicorp/consul_template/models.py
  src/bilder/components/hashicorp/templates/consul-template.service.j2
  src/bilder/components/hashicorp/templates/vault.service.j2
  src/bilder/components/hashicorp/vault/models.py
  src/bilder/images/airbyte/deploy.py
  src/bilder/images/celery_monitoring/deploy.py
  src/bilder/images/dagster/deploy.py
  src/bilder/images/docker_baseline_ami/deploy.py
  src/bilder/images/edx_notes/deploy.py
  src/bilder/images/edxapp_v2/deploy.py
  src/bilder/images/forum/deploy.py
  src/bilder/images/keycloak/deploy.py
  src/bilder/images/odl_video_service/deploy.py
  src/bilder/images/redash/deploy.py
  src/bilder/images/semantic/deploy.py
  src/bilder/images/xqueue/deploy.py
  src/bilder/images/xqwatcher/deploy.py
  src/bilder/lib/model_helpers.py
Labels: bug, DevOps, Needs Review, product:infrastructure

#2499 Updated the odl wildcard certificate
  src/bridge/secrets/vault/secrets.ci.yaml
  src/bridge/secrets/vault/secrets.production.yaml
  src/bridge/secrets/vault/secrets.qa.yaml
Labels: DevOps, Maintenance

#2510 Adding vault-agent restarts to many classes of server.
  src/bilder/images/apisix/deploy.py
  src/bilder/images/celery_monitoring/deploy.py
  src/bilder/images/codejail/deploy.py
  src/bilder/images/dagster/deploy.py
  src/bilder/images/edx_notes/deploy.py
  src/bilder/images/edxapp_v2/deploy.py
  src/bilder/images/forum/deploy.py
  src/bilder/images/keycloak/deploy.py
  src/bilder/images/odl_video_service/deploy.py
  src/bilder/images/redash/deploy.py
  src/bilder/images/semantic/deploy.py
  src/bilder/images/xqueue/deploy.py
  src/bilder/images/xqwatcher/deploy.py
Labels: bug, DevOps

#2512 feat(xPro): add EMERITUS_API_KEY and feature flag
  src/bridge/secrets/xpro/secrets.ci.yaml
  src/bridge/secrets/xpro/secrets.production.yaml
  src/bridge/secrets/xpro/secrets.qa.yaml
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.Production.yaml
  src/ol_infrastructure/applications/xpro/__main__.py
Labels: Waiting on Author

#2514 Md/2358 pt2
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.apps.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.apps.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.apps.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.celery_monitoring.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.celery_monitoring.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.celery_monitoring.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitopen.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitopen.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitx-staging.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitx-staging.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitx-staging.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitx.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitx.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitx.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitxonline.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitxonline.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.xpro.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.xpro.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.xpro.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/__main__.py
Labels: DevOps, Maintenance, Infrastructure

#2515 Added mailgun SMTP configs for Open realm
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.CI.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: enhancement, DevOps

#2516 celery_monitoring consul fixes
  src/bilder/images/celery_monitoring/files/.env.tmpl
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.celery_monitoring.Production.yaml
Labels: bug, DevOps

#2521 posthog action secrets for mitopen
  src/bridge/secrets/mitopen/secrets.production.yaml
  src/bridge/secrets/mitopen/secrets.qa.yaml
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: DevOps, product:mit-open

#2520 feat: added waffle flag to hide taxonomies in residential
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.QA.yaml
Labels: Needs Review

#2524 Superset config for Keycloak token
  src/ol_superset/pythonpath/superset_config.py
Labels: Data, DevOps

#2526 Add api/app urls to mit open env vars
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.Production.yaml
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.QA.yaml
Labels: Needs Review
