Repository mitodl/ol-infrastructure, pull requests merged in 2024-11, with the labels that each got.

#2767 EKS Trustrole improvements
  src/ol_infrastructure/components/aws/eks.py
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
Labels: bug, enhancement, DevOps

#2768 Md/vantage agent
  src/bridge/lib/versions.py
  src/bridge/secrets/vault/secrets.ci.yaml
  src/bridge/secrets/vault/secrets.production.yaml
  src/bridge/secrets/vault/secrets.qa.yaml
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/substructure/aws/eks/__main__.py
  src/ol_infrastructure/substructure/aws/eks/traefik_vault_policy.hcl
  src/ol_infrastructure/substructure/aws/eks/vantage_vault_policy.hcl
Labels: enhancement, DevOps, Needs Review

#2773 Create GIT_REPO_EXPORT_DIR for the final docker image - edxapp
  dockerfiles/openedx-edxapp/Earthfile
Labels: bug, DevOps, Open edX, product:mitx-online, product:xpro, product:residential, project:open-edx

#2776 feat: add ORA settings help URL
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/cms_only.yml.tmpl
Labels: Needs Review

#2779 Update OLL_LEARNING_COURSE_BUCKET_PREFIX
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: Needs Review

#2785 Store public Keycloak cert in vault - part 1
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps, Needs Review, product:data-platform

#2783 Tag vault iam roles
  poetry.lock
  pyproject.toml
  src/ol_infrastructure/applications/airbyte/__main__.py
  src/ol_infrastructure/applications/bootcamps/__main__.py
  src/ol_infrastructure/applications/micromasters/__main__.py
  src/ol_infrastructure/applications/mitlearn/__main__.py
  src/ol_infrastructure/applications/mitxonline/__main__.py
  src/ol_infrastructure/applications/ocw_studio/__main__.py
  src/ol_infrastructure/applications/odl_video_service/__main__.py
  src/ol_infrastructure/applications/xpro/__main__.py
  src/ol_infrastructure/components/services/vault.py
Labels: DevOps

#2791 Resolve edxapp xpro login issue
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/lms_only.yml.tmpl
Labels: DevOps

#2797 Md/install alloy
  src/ol_infrastructure/applications/open_metadata/__main__.py
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/substructure/aws/eks/ALLOY.md
  src/ol_infrastructure/substructure/aws/eks/__main__.py
  src/ol_infrastructure/substructure/aws/eks/operations_vault_policy.hcl
  src/ol_infrastructure/substructure/vault/secrets/__main__.py
Labels: enhancement, DevOps, Needs Review, Monitoring and Alerting

#2798 Keycloak upgrade fix
  src/bilder/images/keycloak/files/.env.tmpl
  src/bilder/images/keycloak/files/docker-compose.yaml
Labels: DevOps

#2802 Add access_logs to Keycloak traefik
  src/bilder/images/keycloak/deploy.py
  src/bilder/images/keycloak/files/docker-compose.yaml
Labels: DevOps

#2563 Initial PR for Vault local dev config
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/vault/policies/developer/local_developer_policy.hcl
  src/ol_infrastructure/substructure/vault/secrets/Pulumi.substructure.vault.secrets.operations.QA.yaml
  src/ol_infrastructure/substructure/vault/secrets/__main__.py
Labels: enhancement, DevOps
