Repository mitodl/ol-infrastructure, pull requests merged in 2024-08, with the labels that each got.

#2585 hq issue 5109
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: enhancement, DevOps, Needs Review, product:mit-open

#2557 Tika build fixes
  src/bilder/images/tika/deploy.py
  src/bilder/images/tika/files/docker-compose.yaml.j2
  src/ol_concourse/pipelines/infrastructure/tika/packer_pulumi_pipeline.py
Labels: enhancement, DevOps, Infrastructure, Tech Debt, product:mit-open

#2592 initial k8s networking changes
  src/ol_infrastructure/components/aws/olvpc.py
  src/ol_infrastructure/infrastructure/aws/network/Pulumi.infrastructure.aws.network.CI.yaml
  src/ol_infrastructure/infrastructure/aws/network/Pulumi.infrastructure.aws.network.Production.yaml
  src/ol_infrastructure/infrastructure/aws/network/Pulumi.infrastructure.aws.network.QA.yaml
  src/ol_infrastructure/infrastructure/aws/network/__main__.py
Labels: enhancement, DevOps

#2503 Update OLL bucket prefix for mitopen
  src/ol_infrastructure/applications/mitopen/__main__.py
Labels: Waiting on Author

#2608 Add SESSION_COOKIE_NAME to mitlearn
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitlearn.QA.yaml
Labels: Needs Review

#2582 Vault DB user provisioning revisit - #2556
  src/ol_infrastructure/applications/edxapp/__main__.py
  src/ol_infrastructure/applications/mitopen/__main__.py
  src/ol_infrastructure/applications/open_discussions/__main__.py
  src/ol_infrastructure/components/services/vault.py
  src/ol_infrastructure/lib/vault.py
Labels: bug, enhancement, DevOps, Needs Review, Infrastructure

#2611 update open catalog urls for ocw-studio
  src/ol_infrastructure/applications/ocw_studio/Pulumi.applications.ocw_studio.Production.yaml
  src/ol_infrastructure/applications/ocw_studio/Pulumi.applications.ocw_studio.QA.yaml
Labels: Needs Review

#2626 Swapping out the PostHog project ID for QA
  src/bridge/secrets/mitopen/secrets.qa.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
Labels: Needs Review

#2618 renaming mitopen->mitlearn rds instance
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: enhancement, DevOps, Maintenance, Tech Debt, product:mit-open

#2627 Add MITPE_BASE_API_URL to mitlearn settings/env
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: Needs Review

#2629 Removing google, googlebot, and bingbot from the prerender.io redirect.
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: enhancement, DevOps, product:mit-open

#2631 Md/s3 replication open to learn
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: DevOps, product:mit-open

#2632 Updated fastly to point to the not-legacy s3 application bucket.
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: DevOps, Infrastructure, product:mit-open

#2633 k8s networking for the ci operations_vpc
  src/ol_concourse/pipelines/infrastructure/heroku_dyno_reset/pipeline.py
  src/ol_infrastructure/infrastructure/aws/network/Pulumi.infrastructure.aws.network.CI.yaml
  src/ol_infrastructure/infrastructure/aws/network/__main__.py
Labels: enhancement, DevOps, Infrastructure

#2634 Add SEE_API_ENABLED env setting with different values for RC, prod
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
Labels: Needs Review

#2628 feat: remove certificate link from resedential course authoring mfe
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: Needs Review

#2640 Enable the Sloan API ETL on production
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
Labels: Needs Review
