Repository mitodl/ol-infrastructure, pull requests merged in 2024-12, with the labels that each got.

#2819 Added a Vault QA sandbox mount for secrets sharing
  src/ol_infrastructure/substructure/vault/policies/developer/local_developer_policy.hcl
  src/ol_infrastructure/substructure/vault/secrets/__main__.py
Labels: DevOps

#2820 Tweaks for vault/keycloak OIDC work
  src/ol_infrastructure/substructure/keycloak/__main__.py
  src/ol_infrastructure/substructure/vault/secrets/Pulumi.substructure.vault.secrets.operations.QA.yaml
Labels: DevOps

#2822 Enable PKCE for OIDC clients
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#2826 Resize edxapp mitxonline prod workers
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitxonline.Production.yaml
Labels: DevOps

#2823 config: change the social auth backend name in xpro
  dockerfiles/openedx-edxapp/pip_package_lists/sumac/xpro.txt
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/lms_only.yml.tmpl
Labels: Waiting on Author

#2829 openai config updates for learn
  src/bridge/secrets/mitopen/secrets.production.yaml
  src/bridge/secrets/mitopen/secrets.qa.yaml
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: enhancement, DevOps, product:mit-open

#2830 config, fix: Added required settings to run daily digest in mitxonline
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#2824 config: add MITXPRO_OAUTH_PROVIDER and OPENEDX_SOCIAL_LOGIN_PATH in xpro RC env
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.CI.yaml
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.QA.yaml
Labels: Needs Review

#2840 Change emailOptIn default to '1'
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: Needs Review

#2843 fix: pinning openedx companion auth to fix authentication in mitxonline
  dockerfiles/openedx-edxapp/pip_package_lists/master/mitxonline.txt
Labels: Needs Review

#2844 fix: email for daily digest
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#2848 config: add notification settings in daily digest
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#2851 UE API Client pipeline: install yarn explicitly
  src/ol_concourse/pipelines/libraries/scripts/unified-ecommerce-api-clients-publish-node.sh
Labels: Needs Review

#2855 config: change mitxonline provider in QA
  src/ol_infrastructure/applications/mitxonline/Pulumi.applications.mitxonline.QA.yaml
Labels: Needs Review

#2856 config: pin openedx-companion-auth version to 1.1.0 in mitxonline
  dockerfiles/openedx-edxapp/pip_package_lists/master/mitxonline.txt
Labels: Needs Review

#2857 config: add MITXPRO_OAUTH_PROVIDER and OPENEDX_SOCIAL_LOGIN_PATH in xpro prod env
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.Production.yaml
Labels: Needs Review

#2860 UE API Client: more fixes for the publishing workflow
  src/ol_concourse/pipelines/libraries/scripts/unified-ecommerce-api-clients-publish-node.sh
Labels: Needs Review

#2863 config: enable new studio mfe in mitx all envs
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.CI.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.Production.yaml
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.QA.yaml
Labels: Needs Review

#2864 Fix SCIM admin console
  src/bilder/images/keycloak/files/docker-compose.yaml
Labels: DevOps

#2861 EKS Wildcard cert fixes
  src/ol_infrastructure/substructure/aws/eks/__main__.py
  src/ol_infrastructure/substructure/aws/eks/operations_vault_policy.hcl
Labels: bug, enhancement, Infrastructure
