Repository mitodl/ol-infrastructure, pull requests merged in 2025-09, with the labels that each got.

#3559 fix: strip Authorization header before sending upstream
  src/ol_infrastructure/applications/ocw_site/__main__.py
  src/ol_infrastructure/applications/ocw_site/snippets/strip_cookies.vcl
  src/ol_infrastructure/applications/ocw_site/snippets/strip_cookies_and_authorization.vcl
Labels: Needs Review

#3516 feat: custom certificate status slot added for custom message
  src/bridge/settings/openedx/mfe/slot_config/xpro/common-mfe-config.env.jsx
Labels: Waiting on Author

#3555 Starburst roles using Pulumi
  src/bridge/secrets/starburst/secrets.production.yaml
  src/ol_infrastructure/applications/starburst/Pulumi.applications.starburst.Production.yaml
  src/ol_infrastructure/applications/starburst/Pulumi.yaml
  src/ol_infrastructure/applications/starburst/__init__.py
  src/ol_infrastructure/applications/starburst/__main__.py
  src/ol_infrastructure/lib/data/__init__.py
  src/ol_infrastructure/lib/data/dbt.py
  src/ol_infrastructure/providers/starburst/__init__.py
  src/ol_infrastructure/providers/starburst/api_client.py
  src/ol_infrastructure/providers/starburst/privilege_builders.py
  src/ol_infrastructure/providers/starburst/role_provider.py
Labels: Data, DevOps

#3585 chore(deps): upgrade git auto export
  dockerfiles/openedx-edxapp/pip_package_lists/master/mitx-staging.txt
  dockerfiles/openedx-edxapp/pip_package_lists/master/mitx.txt
  dockerfiles/openedx-edxapp/pip_package_lists/master/mitxonline.txt
  dockerfiles/openedx-edxapp/pip_package_lists/teak/mitx-staging.txt
  dockerfiles/openedx-edxapp/pip_package_lists/teak/mitx.txt
  dockerfiles/openedx-edxapp/pip_package_lists/teak/xpro.txt
Labels: Waiting on Author

#3589 feat: Exporting the notes DNS name and security group id
  src/ol_infrastructure/applications/edx_notes/__main__.py
Labels: enhancement

#3591 fix: typo in xPro certificate status slot
  src/bridge/settings/openedx/mfe/slot_config/xpro/common-mfe-config.env.jsx
Labels: Waiting on Author

#3590 config: remove the course org and number from edx header
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/common-mfe-config.env.jsx
Labels: Waiting on Author

#3608 fix: redirect to the original page after login in mitxonline learning MFE
  src/bridge/settings/openedx/mfe/slot_config/Footer.jsx
Labels: Waiting on Author
