Repository mitodl/ol-infrastructure, pull requests merged in 2025-03, with the labels that each got.

#2997 posthog for learn-ai
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.Production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
  src/ol_infrastructure/applications/learn_ai/__main__.py
Labels: Needs Review

#3007 Point to RC search from CI/RC learn-ai
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.CI.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
Labels: Needs Review

#3009 Disable Renovate automerge in ocw-course-publisher Dockerfile
  dockerfiles/ocw/node-hugo/Dockerfile
  renovate.json5
Labels: Needs Review

#3011 pass GIT_HASH build arg to learn-ai builds
  src/ol_concourse/pipelines/infrastructure/learn_ai/docker_pulumi.py
Labels: Needs Review

#3012 Sentry configs for learn-ai
  src/bridge/secrets/learn_ai/secrets.ci.yaml
  src/bridge/secrets/learn_ai/secrets.production.yaml
  src/bridge/secrets/learn_ai/secrets.qa.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.CI.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.Production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
Labels: DevOps

#3013 Add celery workers for learn-ai
  src/ol_infrastructure/applications/learn_ai/__main__.py
Labels: enhancement, DevOps

#3016 session secret for learn-ai
  src/ol_infrastructure/applications/learn_ai/__main__.py
Labels: bug, DevOps

#3018 Fixing login_helper.py for Dev access to EKS
  src/ol_infrastructure/substructure/vault/auth/__main__.py
  src/ol_infrastructure/substructure/vault/policies/github/software_engineer.hcl
Labels: bug, DevOps

#3025 feat: update ol_openedx_chat settigs
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#3036 Md/learn ai fastly stuff
  src/ol_infrastructure/applications/learn_ai/__main__.py
Labels: bug, DevOps

#3032 Different session cookie names for learn, learn-ai, xpro, mitxonline
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.CI.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.Production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
  src/ol_infrastructure/applications/mitxonline/Pulumi.applications.mitxonline.Production.yaml
  src/ol_infrastructure/applications/mitxonline/Pulumi.applications.mitxonline.QA.yaml
Labels: Needs Review

#3037 feat: enable other course settings for mitxonline edx
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#3030 added a resource component for media convert
  src/ol_infrastructure/applications/ocw_studio/__main__.py
  src/ol_infrastructure/applications/odl_video_service/__main__.py
  src/ol_infrastructure/components/aws/mediaconvert.py
Labels: Needs Review, product:ocw

#3038 Remove stray quote
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
Labels: Needs Review

#3034 Md/hq issue 6892 2
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.CI.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.Production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
  src/ol_infrastructure/applications/learn_ai/__main__.py
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
  src/ol_infrastructure/applications/mitlearn/__main__.py
  src/ol_infrastructure/applications/unified_ecommerce/Pulumi.applications.unified_ecommerce.CI.yaml
  src/ol_infrastructure/applications/unified_ecommerce/Pulumi.applications.unified_ecommerce.Production.yaml
  src/ol_infrastructure/applications/unified_ecommerce/Pulumi.applications.unified_ecommerce.QA.yaml
  src/ol_infrastructure/applications/unified_ecommerce/__main__.py
Labels: enhancement, DevOps

#3048 Test adding renew_access_token_on_expiry on logout
  src/ol_infrastructure/applications/learn_ai/__main__.py
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: DevOps

#3051 Rename SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS to ALLOWED_REDIRECT_HOSTS (mit-learn)
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: Needs Review

#3053 Md/apisix component resources v1
  src/ol_infrastructure/applications/mitlearn/__main__.py
  src/ol_infrastructure/components/services/k8s.py
Labels: enhancement, DevOps, Design

#3061 Unified Ecommerce: Some minor config changes
  src/bridge/secrets/unified_ecommerce/secrets.ci.yaml
  src/bridge/secrets/unified_ecommerce/secrets.qa.yaml
  src/ol_infrastructure/applications/unified_ecommerce/Pulumi.applications.unified_ecommerce.CI.yaml
  src/ol_infrastructure/applications/unified_ecommerce/Pulumi.applications.unified_ecommerce.Production.yaml
  src/ol_infrastructure/applications/unified_ecommerce/Pulumi.applications.unified_ecommerce.QA.yaml
  src/ol_infrastructure/applications/unified_ecommerce/__main__.py
Labels: Needs Review

#3071 Enable OTEL on learn-ai
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.Production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
Labels: DevOps, Waiting on Author

#3066 feat: update ol_openedx_chat settings & @mitodl/smoot-design version for learning MFE
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/learning-mfe-config.env.jsx
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.Production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
  src/ol_infrastructure/applications/learn_ai/__main__.py
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: Needs Review

#3072 certificate component resource for eks apps
  src/ol_infrastructure/applications/mitlearn/__main__.py
  src/ol_infrastructure/components/services/cert_manager.py
Labels: enhancement, DevOps

#3057 feat: add external course sync email recipients
  src/bridge/secrets/xpro/secrets.production.yaml
  src/bridge/secrets/xpro/secrets.qa.yaml
  src/ol_infrastructure/applications/xpro/__main__.py
Labels: Waiting on Author
