Repository mitodl/ol-infrastructure, pull requests merged in 2025-02, with the labels that each got.

#2930 Small cleanups for unified-ecommerce stacks
  src/bridge/lib/magic_numbers.py
  src/ol_infrastructure/applications/unified_ecommerce/__main__.py
Labels: enhancement, DevOps

#2947 EKS Access overhaul
  src/ol_infrastructure/infrastructure/aws/eks/KUBE_CONFIG_SETUP.md
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.CI.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.QA.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.data.CI.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.data.QA.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.operations.CI.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.operations.QA.yaml
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/infrastructure/aws/eks/generate_kube_config.py
  src/ol_infrastructure/lib/aws/iam_helper.py
Labels: enhancement, DevOps

#2954 Add Learn AI endpoints for GitHub Actions
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: Needs Review

#2956 Learn-AI updates - Production and Bedrock IAM
  poetry.lock
  src/bridge/secrets/learn_ai/secrets.production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.Production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
  src/ol_infrastructure/applications/learn_ai/__main__.py
Labels: DevOps

#2953 update production qdrant host
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
Labels: Needs Review

#2958 Update OVS support emails to ol-engineering-support@mit.edu
  src/bilder/images/odl_video_service/files/.env.tmpl
Labels: Needs Review

#2978 GitHub Actions env vars for Posthog replay
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: product:mit-open

#2786 Store public Keycloak cert in vault - part 2
  src/ol_superset/pythonpath/superset_config.py
Labels: DevOps, Needs Review, do not merge, product:data-platform

#2866 refactor: Update MFE builds to include configurable plugin slot configs
  src/bridge/settings/openedx/mfe/slot_config/mitx/learning.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitx/simple.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/learning.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/simple.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/xpro/learning.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/xpro/simple.env.jsx
  src/bridge/settings/openedx/types.py
  src/bridge/settings/openedx/version_matrix.py
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Waiting on Author

#2975 EKS Developer Overhaul mk2
  src/bridge/lib/magic_numbers.py
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/infrastructure/aws/eks/generate_kube_config.py
  src/ol_infrastructure/infrastructure/aws/eks/login_helper.py
  src/ol_infrastructure/infrastructure/aws/iam/__main__.py
  src/ol_infrastructure/infrastructure/vault/__main__.py
  src/ol_infrastructure/substructure/vault/auth/__main__.py
  src/ol_infrastructure/substructure/vault/policies/github/software_engineer.hcl
Labels: enhancement, DevOps, Design

#2980 pod name labels on logs
  src/ol_infrastructure/substructure/aws/eks/__main__.py
Labels: DevOps, Monitoring and Alerting

#2990 Refactor for better readability
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.CI.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#2992 Fix missing vault sso values
  src/ol_infrastructure/substructure/keycloak/__main__.py
Labels: DevOps

#2993 Upgrade Hugo, Go, Node for ocw-course-publisher
  dockerfiles/ocw/node-hugo/Dockerfile
  dockerfiles/ocw/node-hugo/README.md
  dockerfiles/ocw/node-hugo/tag
  pipelines/ocw/docker-image-pipeline.yml
  renovate.json5
Labels: Needs Review

#2983 Use a different suffix for logout url when apisix is enabled on mit-learn
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: Waiting on Author
