Repository mitodl/ol-infrastructure, pull requests merged in 2025-01, with the labels that each got.

#2868 config: enable proctor exam settings in MITxOnline Studio
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
Labels: Needs Review

#2873 Add values for open-discussions keycloak env vars
  src/ol_infrastructure/applications/open_discussions/Pulumi.applications.open_discussions.Production.yaml
Labels: Needs Review

#2877 revert new Studio MFE waffle flags in production
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.mitx.Production.yaml
Labels: Needs Review

#2862 APISix ingress controller in eks
  src/bridge/lib/versions.py
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.CI.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.Production.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.QA.yaml
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/infrastructure/aws/eks/files/omd_d_values.yaml
  src/ol_infrastructure/infrastructure/aws/eks/files/omd_notes.txt
Labels: enhancement, DevOps, Infrastructure

#2858 config: change mitxonline provider in Prod
  src/ol_infrastructure/applications/mitxonline/Pulumi.applications.mitxonline.Production.yaml
Labels: Needs Review

#2875 refactor: remove ENABLE_TAXES_DISPLAY flag for xpro
  src/ol_infrastructure/applications/xpro/__main__.py
Labels: Needs Review

#2892 Simplified the k8s provider management / creation.
  src/ol_infrastructure/applications/airbyte/__main__.py
  src/ol_infrastructure/applications/open_metadata/__main__.py
  src/ol_infrastructure/lib/aws/eks_helper.py
Labels: enhancement, DevOps

#2893 Added configurations to setup unified ecommerce in keycloak.
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.CI.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
Labels: DevOps

#2876 config, fix: Add COURSE_LIVE_HELP_URL in mitx/cms_only.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitx/cms_only.yml.tmpl
Labels: Needs Review

#2902 refactor(xPRO): remove FEATURE_ENABLE_EXTERNAL_COURSE_SYNC
  src/ol_infrastructure/applications/xpro/Pulumi.applications.xpro.Production.yaml
  src/ol_infrastructure/applications/xpro/__main__.py
Labels: Needs Review

#2903 refactor(xPRO): remove FEATURE_COURSE_DROPDOWN
  src/ol_infrastructure/applications/xpro/__main__.py
Labels: Needs Review

#2904 revert: feature flag removal
  src/ol_infrastructure/applications/xpro/__main__.py
Labels: Needs Review

#2828 Md/unifed ecomm
  src/bridge/secrets/unified_ecommerce/secrets.ci.yaml
  src/bridge/secrets/unified_ecommerce/secrets.qa.yaml
  src/ol_concourse/lib/models/pipeline.py
  src/ol_concourse/lib/models/resource.py
  src/ol_concourse/lib/resources.py
  src/ol_concourse/pipelines/infrastructure/unified_ecommerce/__init__.py
  src/ol_concourse/pipelines/infrastructure/unified_ecommerce/docker_pulumi.py
  src/ol_concourse/pipelines/libraries/unified_ecommerce_api_clients.py
  src/ol_infrastructure/applications/unified_ecommerce/Pulumi.applications.unified_ecommerce.CI.yaml
  src/ol_infrastructure/applications/unified_ecommerce/Pulumi.applications.unified_ecommerce.QA.yaml
  src/ol_infrastructure/applications/unified_ecommerce/Pulumi.yaml
  src/ol_infrastructure/applications/unified_ecommerce/__init__.py
  src/ol_infrastructure/applications/unified_ecommerce/__main__.py
  src/ol_infrastructure/applications/unified_ecommerce/ecommerce_policy.hcl
  src/ol_infrastructure/applications/unified_ecommerce/files/web.conf
  src/ol_infrastructure/lib/aws/cache_helper.py
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.CI.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.Production.yaml
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.QA.yaml
Labels: enhancement, DevOps, Needs Review

#2907 decomm standalone apisix
  src/bilder/images/apisix/__init__.py
  src/bilder/images/apisix/apisix.pkr.hcl
  src/bilder/images/apisix/deploy.py
  src/bilder/images/apisix/files/cloud-cli-configure.service
  src/bilder/images/apisix/files/cloud-cli-deploy.service
  src/bilder/images/apisix/files/supplemental_config.yaml
  src/ol_concourse/pipelines/infrastructure/apisix/BUILD
  src/ol_concourse/pipelines/infrastructure/apisix/__init__.py
  src/ol_concourse/pipelines/infrastructure/apisix/packer_pulumi_pipeline.py
  src/ol_infrastructure/applications/apisix/Pulumi.applications.apisix.CI.yaml
  src/ol_infrastructure/applications/apisix/Pulumi.applications.apisix.Production.yaml
  src/ol_infrastructure/applications/apisix/Pulumi.applications.apisix.QA.yaml
  src/ol_infrastructure/applications/apisix/Pulumi.yaml
  src/ol_infrastructure/applications/apisix/__init__.py
  src/ol_infrastructure/applications/apisix/__main__.py
  src/ol_infrastructure/applications/apisix/apisix_gateway_policy.hcl
Labels: DevOps, Infrastructure, Tech Debt

#2923 Remove User-Agent from Fastly cache key hash
  src/ol_infrastructure/applications/mitlearn/__main__.py
Labels: Needs Review, product:mit-open

#2926 Md/psg attempt 2
  poetry.lock
  pyproject.toml
  src/ol_infrastructure/applications/unified_ecommerce/__main__.py
  src/ol_infrastructure/components/aws/olvpc.py
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.CI.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.Production.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.QA.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.data.CI.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.data.Production.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.data.QA.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.operations.CI.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.operations.Production.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.operations.QA.yaml
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/infrastructure/aws/network/Pulumi.infrastructure.aws.network.CI.yaml
  src/ol_infrastructure/infrastructure/aws/network/Pulumi.infrastructure.aws.network.Production.yaml
  src/ol_infrastructure/infrastructure/aws/network/Pulumi.infrastructure.aws.network.QA.yaml
  src/ol_infrastructure/infrastructure/aws/network/README.md
  src/ol_infrastructure/infrastructure/aws/network/__main__.py
  src/ol_infrastructure/lib/aws/eks_helper.py
Labels: enhancement, DevOps, Needs Review

#2917 Course asset routes added for allowed urls
  src/bilder/images/edxapp_v2/templates/edxapp/mitx-staging/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitx/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/xpro/common_values.yml.tmpl
Labels: Needs Review
