Repository mitodl/ol-infrastructure, pull requests merged in 2025-06, with the labels that each got.

#3250 chore: update git auto export to fix dependency conflict
  dockerfiles/openedx-edxapp/pip_package_lists/master/mitx-staging.txt
  dockerfiles/openedx-edxapp/pip_package_lists/master/mitx.txt
  dockerfiles/openedx-edxapp/pip_package_lists/master/mitxonline.txt
  dockerfiles/openedx-edxapp/pip_package_lists/teak/mitx-staging.txt
  dockerfiles/openedx-edxapp/pip_package_lists/teak/mitx.txt
  dockerfiles/openedx-edxapp/pip_package_lists/teak/xpro.txt
Labels: Waiting on Author

#3251 adding optional fastly purging for k8s_apps pipelines
  src/ol_concourse/lib/jobs/infrastructure.py
  src/ol_concourse/pipelines/infrastructure/k8s_apps/docker_pulumi.py
Labels: DevOps

#3256 feat: add learn urls for MIT_ET courses
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/common-mfe-config.env.jsx
Labels: Waiting on Author

#3268 Install and configure KEDA
  src/ol_infrastructure/substructure/aws/eks/__main__.py
Labels: enhancement, DevOps

#3284 fix: add ENABLE_VIDEO_UPLOAD_PAGE_LINK_IN_CONTENT_DROPDOWN feature flag
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: Waiting on Author

#3283 KEDA networking changes
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/infrastructure/aws/network/__main__.py
Labels: DevOps

#3257 feat: add MITx branding with slots
  src/bridge/settings/openedx/mfe/slot_config/mitx-staging/common-mfe-config.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitx-styles.scss
  src/bridge/settings/openedx/mfe/slot_config/mitx/common-mfe-config.env.jsx
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Needs Review, Waiting on Author

#3331 fix: paragon styles issue
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Needs Review
