Repository mitodl/ol-infrastructure, pull requests merged in 2025-08, with the labels that each got.

#3439 add some mongodb host string outputs
  src/ol_infrastructure/infrastructure/mongodb_atlas/__main__.py
Labels: DevOps

#3445 revert: 'fix: changed the dashboard url for UAI courses to point to mitxonline dashboard'
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/common-mfe-config.env.jsx
Labels: Waiting on Author

#3463 config: add ai tutor xblock config
  src/bilder/images/edxapp_v2/templates/edxapp/mitx-staging/common_values.yml.tmpl
  src/bilder/images/edxapp_v2/templates/edxapp/mitx/common_values.yml.tmpl
Labels: Needs Review

#3492 fix: enable the breadcrump slot only for MITxOnline
  src/bridge/settings/openedx/mfe/slot_config/learning-mfe-config.env.jsx
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Waiting on Author

#3493 config: remove mit_et from UAI_COURSE_KEY_FORMATS
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/common-mfe-config.env.jsx
Labels: Waiting on Author

#3477 config: update mitxonline footer to use learn links in both MFE and Legacy templates
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/common-mfe-config.env.jsx
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: Waiting on Author

#3515 config: remove course outline sidebar trigger btn from mitxonline learning mfe
  src/bridge/settings/openedx/mfe/slot_config/learning-mfe-config.env.jsx
Labels: Waiting on Author

#3520 Fix up AI citation settings
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.Production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
  src/ol_infrastructure/applications/mit_learn/Pulumi.applications.mit_learn.Production.yaml
  src/ol_infrastructure/applications/mit_learn/Pulumi.applications.mit_learn.QA.yaml
Labels: Needs Review

#3521 CANVAS_SYLLABUS_DEMO_READABLE_IDS setting for learn-ai
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.CI.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.Production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
Labels: Needs Review
