Repository mitodl/ol-infrastructure, pull requests merged in 2025-05, with the labels that each got.

#3161 Frontend learn-ai env vars for choosing recommendation search backend
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.CI.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.Production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
Labels: Needs Review

#3163 Md/apisix stab and misc eks stuff
  src/ol_infrastructure/applications/learn_ai/__main__.py
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.CI.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.Production.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.QA.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.data.CI.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.data.Production.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.data.QA.yaml
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
Labels: bug, enhancement, DevOps

#3182 removed prefix and duplicate variables
  src/bilder/images/odl_video_service/files/.env.tmpl
Labels: Needs Review

#3184 Update env.config.js to avoid double-bundling smoot-design
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/learning-mfe-config.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/xpro/learning-mfe-config.env.jsx
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Waiting on Author

#3191 Resource usage tweaks
  src/ol_infrastructure/applications/mit_learn/Pulumi.applications.mit_learn.CI.yaml
  src/ol_infrastructure/applications/mit_learn/Pulumi.applications.mit_learn.Production.yaml
  src/ol_infrastructure/applications/mit_learn/Pulumi.applications.mit_learn.QA.yaml
  src/ol_infrastructure/applications/mit_learn/__main__.py
  src/ol_infrastructure/substructure/aws/eks/__main__.py
  src/ol_infrastructure/substructure/aws/eks/karpenter.py
Labels: enhancement, DevOps

#3192 Fix static url path
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/learning-mfe-config.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/xpro/learning-mfe-config.env.jsx
Labels: Needs Review

#3181 AI_PROMPT_CACHE_FUNCTION env var for learn-ai
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.CI.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.Production.yaml
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
Labels: Needs Review

#3194 Fix keycloak caching issue
  src/bilder/images/keycloak/files/cache-ispn-jdbc-ping.xml
  src/bilder/images/keycloak/files/docker-compose.yaml
  src/ol_infrastructure/applications/keycloak/__main__.py
Labels: DevOps

#3207 Resize edxapp xpro QA redis cluster
  src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.QA.yaml
Labels: DevOps

#3205 Md/prometheus operator
  src/bridge/lib/versions.py
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
  src/ol_infrastructure/substructure/aws/eks/__main__.py
  src/ol_infrastructure/substructure/aws/eks/karpenter.py
Labels: enhancement, DevOps, Monitoring and Alerting

#3208 Upgrade all 2.11 opensearch instances to 2.19
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.celery_monitoring.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.celery_monitoring.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.celery_monitoring.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitlearn.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitlearn.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitlearn.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitopen.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitopen.QA.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open_metadata.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open_metadata.Production.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.open_metadata.QA.yaml
Labels: DevOps, Maintenance

#3214 Add keycloakify repo
  src/ol_concourse/pipelines/infrastructure/keycloak/docker_packer_pulumi_pipeline.py
Labels: DevOps, sso

#3224 Md/k8s keyclaok 2
  src/bilder/images/keycloak/__init__.py
  src/bilder/images/keycloak/deploy.py
  src/bilder/images/keycloak/files/.env.tmpl
  src/bilder/images/keycloak/files/cache-ispn-jdbc-ping.xml
  src/bilder/images/keycloak/files/docker-compose.yaml
  src/ol_concourse/pipelines/infrastructure/keycloak/docker_pulumi_pipeline.py
  src/ol_infrastructure/applications/keycloak/Pulumi.applications.keycloak.CI.yaml
  src/ol_infrastructure/applications/keycloak/Pulumi.applications.keycloak.Production.yaml
  src/ol_infrastructure/applications/keycloak/Pulumi.applications.keycloak.QA.yaml
  src/ol_infrastructure/applications/keycloak/__main__.py
Labels: enhancement, DevOps

#3226 Helper script for developer EKS access
  scripts/eks/KUBE_ACCESS.md
  scripts/eks/eks.sh
  scripts/eks/github.example.env
Labels: Needs Review

#3213 feat: update mitxonline edx logos to learn
  src/bilder/images/edxapp_v2/templates/edxapp/mitxonline/common_values.yml.tmpl
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/common-mfe-config.env.jsx
  src/ol_concourse/pipelines/open_edx/mfe/values.py
Labels: Needs Review
