Repository mitodl/ol-infrastructure, pull requests merged in 2025-04, with the labels that each got.

#3082 Keycloak substructure changes needed for mitlearn-ci
  src/ol_infrastructure/substructure/keycloak/Pulumi.substructure.keycloak.CI.yaml
Labels: DevOps

#3079 set Posthog env vars for published OCW sites
  src/ol_infrastructure/applications/ocw_studio/Pulumi.applications.ocw_studio.Production.yaml
  src/ol_infrastructure/applications/ocw_studio/Pulumi.applications.ocw_studio.QA.yaml
Labels: Needs Review

#3093 Set search detail base url for LearnAI RC
  src/ol_infrastructure/applications/learn_ai/Pulumi.applications.learn_ai.QA.yaml
Labels: Needs Review

#3095 Add celery workers to OLApplicationK8s
  src/ol_infrastructure/components/services/k8s.py
Labels: DevOps, Design

#3094 Md/mitlearn ci env
  src/bridge/secrets/mitlearn/secrets.ci.yaml
  src/bridge/secrets/mitlearn/secrets.production.yaml
  src/bridge/secrets/mitlearn/secrets.qa.yaml
  src/bridge/secrets/mitopen
  src/bridge/secrets/opensearch/opensearch.mitlearn.ci.yaml
  src/ol_infrastructure/applications/learn_ai/__main__.py
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.CI.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.QA.yaml
  src/ol_infrastructure/applications/mitlearn/__main__.py
  src/ol_infrastructure/applications/mitlearn/files/uwsgi.ini
  src/ol_infrastructure/applications/mitlearn/files/web.conf
  src/ol_infrastructure/applications/mitlearn/k8s_secrets.py
  src/ol_infrastructure/applications/mitlearn/mitlearn_policy.hcl
  src/ol_infrastructure/applications/unified_ecommerce/__main__.py
  src/ol_infrastructure/components/services/k8s.py
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.CI.yaml
  src/ol_infrastructure/infrastructure/aws/opensearch/Pulumi.infrastructure.aws.opensearch.mitlearn.CI.yaml
Labels: enhancement, DevOps, Design

#3102 Karpenter pre-reqs
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
Labels: enhancement, DevOps

#3107 redis + mitlearn
  src/ol_infrastructure/applications/mitlearn/Pulumi.applications.mitlearn.CI.yaml
  src/ol_infrastructure/applications/mitlearn/__main__.py
  src/ol_infrastructure/applications/mitlearn/k8s_secrets.py
Labels: enhancement, DevOps

#3108 move mitlearn to mit_learn
  src/ol_infrastructure/applications/mit_learn/Pulumi.applications.mitlearn.CI.yaml
  src/ol_infrastructure/applications/mit_learn/Pulumi.applications.mitlearn.Production.yaml
  src/ol_infrastructure/applications/mit_learn/Pulumi.applications.mitlearn.QA.yaml
  src/ol_infrastructure/applications/mit_learn/Pulumi.yaml
  src/ol_infrastructure/applications/mit_learn/__init__.py
  src/ol_infrastructure/applications/mit_learn/__main__.py
  src/ol_infrastructure/applications/mit_learn/files/uwsgi.ini
  src/ol_infrastructure/applications/mit_learn/files/web.conf
  src/ol_infrastructure/applications/mit_learn/k8s_secrets.py
  src/ol_infrastructure/applications/mit_learn/mitlearn_policy.hcl
Labels: enhancement, DevOps

#3105 Set EMBEDDINGS_EXTERNAL_FETCH_USE_WEBDRIVER flag to True
  src/ol_infrastructure/applications/mit_learn/__main__.py
Labels: Needs Review

#3121 Md/mitlearn - image fixup and cutover mechanism
  src/ol_infrastructure/applications/mit_learn/Pulumi.applications.mit_learn.CI.yaml
  src/ol_infrastructure/applications/mit_learn/Pulumi.applications.mit_learn.Production.yaml
  src/ol_infrastructure/applications/mit_learn/Pulumi.applications.mit_learn.QA.yaml
  src/ol_infrastructure/applications/mit_learn/__main__.py
  src/ol_infrastructure/applications/mit_learn/k8s_secrets.py
  src/ol_infrastructure/components/services/k8s.py
Labels: enhancement, DevOps

#3136 Grafana alloy + OTEL metrics networking fix
  src/bridge/lib/magic_numbers.py
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
Labels: bug, DevOps

#3120 refactor: slots config files and add footer slot
  src/bridge/settings/openedx/mfe/slot_config/Footer.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitx-staging/common-mfe-config.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitx-staging/learning.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitx-staging/simple.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitx/common-mfe-config.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitx/learning.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitx/simple.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/common-mfe-config.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/learning-mfe-config.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/learning.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/mitxonline/simple.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/xpro/common-mfe-config.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/xpro/learning-mfe-config.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/xpro/learning.env.jsx
  src/bridge/settings/openedx/mfe/slot_config/xpro/simple.env.jsx
  src/bridge/settings/openedx/types.py
  src/bridge/settings/openedx/version_matrix.py
  src/ol_concourse/pipelines/open_edx/mfe/pipeline.py
Labels: Needs Review

#2995 add OCW_STUDIO_DELETABLE_CONTENT_TYPES
  src/ol_infrastructure/applications/ocw_studio/__main__.py
Labels: Needs Review

#2363 standardize MITx Online support email address
  src/ol_infrastructure/applications/mitxonline/__main__.py
Labels: Needs Review

#3157 rework dev access to eks
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.CI.yaml
  src/ol_infrastructure/infrastructure/aws/eks/Pulumi.infrastructure.aws.eks.applications.QA.yaml
  src/ol_infrastructure/infrastructure/aws/eks/__main__.py
Labels: bug, enhancement, DevOps

#3160 Resolve connection issues
  src/ol_superset/pythonpath/superset_config.py
Labels: bug, Data
